[package]
name = "feature-code-binding-sprites"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
vieww = { workspace = true, features = ["native"] }
vieww-foundation.workspace = true
vieww-widget.workspace = true
feature-harness = { path = "../harness" }
vieww-element.workspace = true
vieww-image.workspace = true

[lints]
workspace = true
