[package]
name = "feature-3d-scene"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
vieww = { workspace = true, features = ["native"] }
vieww-3d.workspace = true
vieww-mesh.workspace = true
vieww-foundation.workspace = true
feature-harness = { path = "../harness" }
vieww-widget.workspace = true

[lints]
workspace = true
