//! studio — **the viewwstudio kit**: the IDE mock every Act III scene is
//! dressed in, rebuilt bespoke for v5 — richer than v2/v3's: a brand mark in
//! the title bar, a file-tree sidebar, a command palette, target chips, and
//! a preview that can host more than the counter (the swarm sheet, the
//! fourier canvas — the demo plates drop *into the layout*, as the reference
//! script demands).
//!
//! The mock is honest about what it is: a vieww widget tree standing in for
//! the product's chrome, rendered by the same rasterizer the product uses —
//! the film's own meta-claim (K5) covers it. The buffers are verbatim
//! grammar from the studio's own docs (`apps/viewwstudio/docs/06-say.md`).

use vieww_foundation::{
    Color, FontWeight, Gradient, Offset, Rect, Size, Sketchbook, TextAlign, TextStyle,
};
use vieww_widget::prelude::*;
use vieww_widget::{Opacity, Painting, PaintWith};

use crate::film_lib::{
    alpha, clamp01, mix, spring_out, tint, xywh, AMBER, FAINT, INK, MINT, MUTED, RED, VIOLET,
    VIOLET_SOFT, CYAN, CYAN_SOFT,
};

use super::{chip, circle_path, group_commas, mono, C_DAMAGE};

// ── Geometry — the studio grid at 1920×1080 ────────────────────────────────

pub const TITLE_H: f32 = 52.0;
pub const STATUS_H: f32 = 46.0;
pub const ACT_W: f32 = 58.0;
/// The file-tree sidebar.
pub const SIDE_W: f32 = 232.0;
/// Editor pane: from the sidebar to the mid gutter.
pub const ED_X0: f32 = ACT_W + SIDE_W;
pub const ED_X1: f32 = 940.0;
/// Preview pane.
pub const PV_X0: f32 = 962.0;
pub const PV_X1: f32 = 1862.0;
/// Code origin (inside gutter).
pub const CODE_X: f32 = 60.0;
pub const CODE_SIZE: f32 = 21.0;
pub const CODE_LH: f32 = 37.0;
/// The preview pane's inner height (the glass).
pub const PV_H: f32 = 924.0;

/// The code plain-text tone — brighter than muted, dimmer than ink.
pub const CODE_PLAIN: Color = Color::rgb(196, 205, 214);

// ── The two buffers — say, and its descent ─────────────────────────────────

/// One tokenized code line: text run + color.
pub type Seg = (&'static str, Color);

/// The counter buffer in say — verbatim grammar from the studio's own
/// `06-say.md` (the film's first shown code; the language is the product's).
pub fn say_lines() -> Vec<Vec<Seg>> {
    let kw = VIOLET_SOFT;
    let st = AMBER;
    let nu = MINT;
    let tx = CODE_PLAIN;
    let pu = MUTED;
    vec![
        vec![("keep ", kw), ("a whole number called ", tx), ("count", tx), (" starting at ", pu), ("0", nu)],
        vec![],
        vec![("screen ", kw), ("\"Home\"", st), (":", pu)],
        vec![("    a column, spaced ", pu), ("16", nu), (", children aligned to the start:", pu)],
        vec![("        a heading ", pu), ("\"Counter\"", st)],
        vec![("        a label ", pu), ("\"Tapped \\(count) times\"", st)],
        vec![("        a button ", pu), ("\"Add one\"", st), (" which when tapped:", pu)],
        vec![("            add ", kw), ("1", nu), (" to count", tx)],
    ]
}

/// The same buffer, descended — the generated Rust, annotated the way
/// `say-codegen` annotates (`// say: file:line`), state held across the
/// switch. The counter never resets through the morph.
pub fn rust_lines() -> Vec<Vec<Seg>> {
    let cm = FAINT;
    let at = VIOLET;
    let kw = VIOLET_SOFT;
    let ty = CYAN;
    let st = AMBER;
    let nu = MINT;
    let tx = CODE_PLAIN;
    let pu = MUTED;
    vec![
        vec![("// say: counter.say — generated by vieww-say-codegen", cm)],
        vec![("#[vieww::keep]", at)],
        vec![("static ", kw), ("COUNT", ty), (": ", pu), ("Signal", ty), ("<", pu), ("u32", ty), ("> = ", pu), ("Signal", ty), ("::new(", pu), ("0", nu), (");", pu)],
        vec![],
        vec![("#[vieww::screen(name = ", at), ("\"Home\"", st), (")]", at)],
        vec![("fn ", kw), ("home", tx), ("() -> ", pu), ("impl Widget", ty), (" {", pu)],
        vec![("    column", ty), ("(", pu), ("16", nu), (").align_start().children([", pu)],
        vec![("        heading", ty), ("(", pu), ("\"Counter\"", st), ("),", pu)],
        vec![("        label", ty), ("(", pu), ("format!(", pu), ("\"Tapped {} times\"", st), (", ", pu), ("*COUNT.get())", tx)],
        vec![("        button", ty), ("(", pu), ("\"Add one\"", st), (").on_tap(||", pu)],
        vec![("            *COUNT.update(", tx), ("|c| c + ", pu), ("1", nu), ("))),", tx)],
        vec![("    ])", pu)],
        vec![("}", pu)],
    ]
}

/// Which buffer the editor holds.
pub enum Code {
    /// say, typed on — `typed` in `[0, 1]` is the type-on progress,
    /// `blink` the caret's 24-in-60 blink phase.
    Say { typed: f32, blink: f32 },
    /// say, base complete, plus scene-provided extra lines (the buffer
    /// growing under live keystrokes — S12). `lines` are already sliced
    /// to whatever the scene wants visible; the caret rides their end.
    SayExt { blink: f32, lines: Vec<Vec<Seg>> },
    /// A bespoke buffer — the demo plates' own say programs (S14/S15):
    /// complete lines, the caret breathing at the end.
    Lines { lines: Vec<Vec<Seg>>, blink: f32 },
    /// Rust, resolving under the sweep — `sweep` in `[0, 1]` is how far the
    /// scan line has crossed the editor; a line flips once it has passed.
    Rust { sweep: f32 },
    /// Nothing yet — the buffer before the first keystroke.
    Empty,
}

/// The resolved display lines for a code state, with (line-flip) progress.
fn display_lines(code: &Code) -> (Vec<Vec<Seg>>, Option<usize>, Option<f32>) {
    match code {
        Code::Say { typed, .. } => {
            let all = say_lines();
            let total: usize = all
                .iter()
                .map(|l| l.iter().map(|(s, _)| s.chars().count()).sum::<usize>())
                .sum();
            let typed_n = (total as f32 * typed.clamp(0.0, 1.0)).round() as usize;
            (all, Some(typed_n), None)
        }
        Code::SayExt { lines, .. } => {
            let mut all = say_lines();
            let extras = lines.clone();
            all.extend(extras);
            let total: usize = all
                .iter()
                .map(|l| l.iter().map(|(s, _)| s.chars().count()).sum::<usize>())
                .sum();
            (all, Some(total), None)
        }
        Code::Lines { lines, .. } => {
            let all = lines.clone();
            let total: usize = all
                .iter()
                .map(|l| l.iter().map(|(s, _)| s.chars().count()).sum::<usize>())
                .sum();
            (all, Some(total), None)
        }
        Code::Rust { sweep } => {
            let say = say_lines();
            let rust = rust_lines();
            let n = rust.len();
            let mut lines = Vec::with_capacity(n);
            for (i, rline) in rust.iter().enumerate() {
                let passed = *sweep >= (i + 1) as f32 / n as f32;
                if passed {
                    lines.push(rline.clone());
                } else if i < say.len() {
                    lines.push(say[i].clone());
                } else {
                    lines.push(vec![]);
                }
            }
            (lines, None, Some(*sweep))
        }
        Code::Empty => (vec![], None, None),
    }
}

// ── The counter app — the preview's default content ────────────────────────

/// The preview's app state, all derived from the film's own clocks.
pub struct App {
    /// The witness counter — what the app shows.
    pub number: u32,
    /// Bloom on the number right after a tap (tap_pulse).
    pub flash: f32,
    /// The dial's presence, `[0, 1]`.
    pub dial: f32,
    /// The spring toy's phase source (absolute film seconds — the spring
    /// never restarts, that is the whole point of the carry).
    pub spring_abs: f32,
    /// The spring toy's presence.
    pub spring: f32,
    /// The error boundary's presence, `[0, 1]` — a boundary, not a crash.
    pub error: f32,
    /// The app's alive-bloom (first paint).
    pub alive: f32,
    /// The column's spacing re-flow (16 → 24) — the carry demonstrated as
    /// layout shift while state holds.
    pub spacing: f32,
    /// The heading's live-edit progress toward its new text (S12).
    pub heading: f32,
}

impl App {
    pub fn new(number: u32, flash: f32, abs: f32) -> App {
        App {
            number,
            flash,
            dial: 0.0,
            spring_abs: abs,
            spring: 0.0,
            error: 0.0,
            alive: 1.0,
            spacing: 0.0,
            heading: 0.0,
        }
    }

    /// The heading's current text — "Counter" edits to "viewwstudio" under
    /// the composer's keystrokes (S12); `heading` is the edit's progress.
    pub fn heading_text(&self) -> String {
        const FROM: &str = "Counter";
        const TO: &str = "viewwstudio";
        let u = clamp01(self.heading);
        if u <= 0.0 {
            return FROM.to_string();
        }
        if u >= 1.0 {
            return TO.to_string();
        }
        // A scramble band crossing the word — the compose made visible.
        let n = TO.chars().count();
        let crossed = (n as f32 * u).round() as usize;
        TO.chars().take(crossed).chain(FROM.chars().skip(crossed.min(FROM.chars().count()))).collect()
    }
}

/// The button's rect in preview-local coordinates — the damage probe's
/// ground truth. One place declares it; the scene and the overlay agree.
pub fn button_rect() -> Rect {
    xywh(237.0, 478.0, 246.0, 64.0)
}

/// A local circle path (the painter's own space).
fn circle_local(cx: f32, cy: f32, r: f32) -> vieww_foundation::Path {
    circle_path(cx, cy, r, 36)
}

/// The preview panel: frosted glass, the app (or a scene's custom sheet)
/// inside. `custom` replaces the counter app when a demo plate drops in.
pub fn preview(app: &App, blur: f32, custom: Option<WidgetNode>) -> WidgetNode {
    let alive = clamp01(app.alive);
    let pane_w = PV_X1 - PV_X0;

    let content = match custom {
        Some(node) => node,
        None => counter_app(app, alive, pane_w),
    };

    // The glass body — frosted, tinted, bordered (light's card grammar).
    let glass = Container::new()
        .size(pane_w, PV_H)
        .radius(18.0)
        .gradient(
            Gradient::vertical().with_dither().with_stops(&[
                (0.0, alpha(mix(Color::WHITE, VIOLET_SOFT, 0.22), 0.055)),
                (0.55, alpha(Color::WHITE, 0.028)),
                (1.0, alpha(mix(Color::WHITE, CYAN_SOFT, 0.28), 0.045)),
            ]),
        )
        .border(vieww_foundation::Border::new(alpha(Color::WHITE, 0.14), 1.0));

    let header = Positioned::new().left(4.0).top(8.0).width(600.0).height(26.0).child(
        Text::new("preview · Home").style(
            TextStyle::new(15.0).monospace().letter_spacing(2.0).color(alpha(MUTED, 0.85)),
        ),
    );

    let pane = Stack::new()
        .push(
            Positioned::new().left(0.0).top(34.0).width(pane_w).height(PV_H).child(glass),
        )
        .push(
            Positioned::new().left(0.0).top(34.0).width(pane_w).height(PV_H).child(content),
        )
        .push(header);

    if blur > 0.05 {
        Filtered::blur(blur).child(pane).into()
    } else {
        pane.into()
    }
}

/// The counter app — heading, label, the number, the button, the toys.
fn counter_app(app: &App, alive: f32, pane_w: f32) -> WidgetNode {
    let number = app.number;
    let flash = app.flash;
    let heading = app.heading_text();
    let heading_a = clamp01(app.heading);
    let spacing_shift = clamp01(app.spacing) * 26.0;

    let num_spring = spring_out(clamp01(flash * 3.0), 12.0, 0.58);
    let num_y = (1.0 - num_spring) * 10.0;
    let num_color = mix(INK, tint(VIOLET_SOFT, 0.3), flash.min(1.0));

    let mut app_stack = Stack::new()
        .push(
            Positioned::new().left(96.0).top(88.0 + spacing_shift * 0.4).width(640.0).height(52.0).child(
                Text::new(heading).style(
                    TextStyle::new(38.0)
                        .weight(FontWeight::Medium)
                        .letter_spacing(1.0)
                        .color(if heading_a > 0.02 && heading_a < 0.98 {
                            tint(VIOLET_SOFT, 0.2)
                        } else {
                            INK
                        }),
                ),
            ),
        )
        .push(
            Positioned::new().left(98.0).top(148.0 + spacing_shift).width(600.0).height(30.0).child(
                Text::new(format!("Tapped {} times", number))
                    .style(TextStyle::new(21.0).monospace().color(MUTED)),
            ),
        )
        .push(
            Positioned::new()
                .left(0.0)
                .top(196.0 + num_y + spacing_shift)
                .width(pane_w)
                .height(190.0)
                .child(
                    Text::new(number.to_string())
                        .style(
                            TextStyle::new(148.0)
                                .monospace()
                                .weight(FontWeight::Medium)
                                .letter_spacing(2.0)
                                .color(num_color),
                        )
                        .align(TextAlign::Center),
                ),
        );

    // The button — its rect is probe-grade (see button_rect); the column's
    // spacing re-flow (S12) shifts it down as the layout breathes.
    let press = 1.0 - 0.06 * flash;
    let br = button_rect();
    app_stack = app_stack.push(
        Positioned::new()
            .left(br.left)
            .top(br.top - 40.0 + spacing_shift)
            .width(br.width())
            .height(br.height())
            .child(
                Container::new()
                    .color(alpha(VIOLET, 0.20 * press))
                    .radius(12.0)
                    .border(vieww_foundation::Border::new(alpha(VIOLET_SOFT, 0.55), 1.4))
                    .child(
                        Text::new("Add one")
                            .style(
                                TextStyle::new(23.0)
                                    .weight(FontWeight::Medium)
                                    .color(tint(VIOLET_SOFT, 0.35)),
                            )
                            .align(TextAlign::Center),
                    ),
            ),
    );

    // The dial — an arc gauge, count over the ladder's full height.
    if clamp01(app.dial) > 0.01 {
        let dial = clamp01(app.dial);
        let cx = 700.0;
        let cy = 150.0;
        let lad = app.number.max(1);
        app_stack = app_stack.push(
            Positioned::new().left(0.0).top(0.0).width(pane_w).height(PV_H).child(
                Opacity::new(dial).child(Painting::sized(
                    Size::new(pane_w, PV_H),
                    PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                        let r = 62.0;
                        book.stroke(circle_local(cx, cy, r), alpha(Color::WHITE, 0.10), 7.0);
                        let sweep = (number as f32 / lad as f32).clamp(0.0, 1.0);
                        if sweep > 0.001 {
                            let mut p = vieww_foundation::Path::new();
                            p.move_to(Offset::new(cx, cy - r));
                            for i in 0..=40 {
                                let a = -std::f32::consts::FRAC_PI_2
                                    + i as f32 / 40.0 * sweep * std::f32::consts::TAU;
                                p.line_to(Offset::new(cx + a.cos() * r, cy + a.sin() * r));
                            }
                            book.stroke(p, alpha(VIOLET_SOFT, 0.85), 7.0);
                        }
                        book.circle(Offset::new(cx, cy), 4.0, tint(VIOLET_SOFT, 0.3));
                    }),
                )),
            ),
        );
    }

    // The spring toy — a bob on a spring line, phase from the session
    // clock. It never restarts (the carry's whole claim).
    if clamp01(app.spring) > 0.01 {
        let spring_p = clamp01(app.spring);
        let spring_abs = app.spring_abs;
        let disp = (spring_abs * 2.4).sin() * 26.0;
        let bx = 240.0;
        let by0 = 560.0;
        app_stack = app_stack.push(
            Positioned::new().left(0.0).top(0.0).width(pane_w).height(PV_H).child(
                Opacity::new(spring_p).child(Painting::sized(
                    Size::new(pane_w, PV_H),
                    PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                        let by = by0 + disp;
                        let mut p = vieww_foundation::Path::new();
                        p.move_to(Offset::new(bx, by0 - 64.0));
                        for i in 0..12 {
                            let k = (i + 1) as f32 / 12.0;
                            let y = by0 - 64.0 + k * (64.0 + (by - by0));
                            let wob = if i % 2 == 0 { 12.0 } else { -12.0 };
                            p.line_to(Offset::new(bx + wob, y));
                        }
                        p.line_to(Offset::new(bx, by));
                        book.stroke(p, alpha(MUTED, 0.55), 1.6);
                        book.circle(Offset::new(bx, by + 8.0), 11.0, tint(VIOLET_SOFT, 0.4));
                        book.stroke(circle_local(bx, by + 8.0, 11.0), alpha(Color::WHITE, 0.25), 1.0);
                        book.rect(xywh(bx - 22.0, by0 - 70.0, 44.0, 5.0), alpha(Color::WHITE, 0.18));
                    }),
                )),
            ),
        );
    }

    // The error boundary — a boundary, not a crash. The preview holds its
    // last good frame beneath the card: nothing is lost, nothing breaks.
    if clamp01(app.error) > 0.01 {
        let e = clamp01(app.error);
        app_stack = app_stack.push(
            Positioned::new().left(96.0).top(96.0).width(660.0).height(420.0).child(
                Opacity::new(e).child(Painting::sized(
                    Size::new(660.0, 420.0),
                    PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                        book.rrect(xywh(0.0, 0.0, 660.0, 420.0), 16.0, alpha(Color::rgb(40, 16, 20), 0.94));
                        book.stroke_rrect(xywh(0.0, 0.0, 660.0, 420.0), 16.0, alpha(RED, 0.45), 1.4);
                        book.rect(xywh(0.0, 0.0, 660.0, 4.0), alpha(RED, 0.8 * e));
                    }),
                )),
            ),
        );
        app_stack = app_stack
            .push(
                Positioned::new().left(136.0).top(150.0).width(560.0).height(40.0).child(
                    Text::new("boundary").style(
                        TextStyle::new(30.0)
                            .monospace()
                            .letter_spacing(3.0)
                            .color(tint(RED, 0.25)),
                    ),
                ),
            )
            .push(
                Positioned::new().left(136.0).top(206.0).width(540.0).height(90.0).child(
                    Text::new(
                        "expected a value after \u{201c}showing\u{d}\nthe preview holds your last good frame",
                    )
                    .style(TextStyle::new(19.0).monospace().color(alpha(INK, 0.8))),
                ),
            );
    }

    // The dormant skeleton — before the first paint, the pane is a dim
    // wireframe of what it is waiting to become.
    let skeleton = Painting::sized(
        Size::new(pane_w, PV_H),
        PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
            let a = 0.16 * (1.0 - alive);
            if a <= 0.005 {
                return;
            }
            book.rrect(xywh(96.0, 96.0, 240.0, 34.0), 6.0, alpha(Color::WHITE, a));
            book.rrect(xywh(98.0, 152.0, 300.0, 18.0), 5.0, alpha(Color::WHITE, a * 0.7));
            book.rrect(xywh(360.0, 210.0, 180.0, 120.0), 10.0, alpha(Color::WHITE, a));
            let br = button_rect();
            book.rrect(
                xywh(br.left, br.top - 40.0, br.width(), br.height()),
                12.0,
                alpha(VIOLET, a * 0.8),
            );
            book.stroke_styled(
                circle_path(br.left + br.width() + 70.0, br.top - 8.0, 14.0, 36),
                alpha(MUTED, a * 2.4),
                2.2,
                vieww_foundation::StrokeStyle::rounded()
                    .dash(vieww_foundation::Dash::even(6.0).offset(alive * 40.0)),
            );
        }),
    );

    let bloom_a = 0.34 * (1.0 - alive).max(0.0) + if alive >= 0.999 { 0.0 } else { 0.05 };
    Stack::new()
        .push(
            Positioned::new().left(0.0).top(0.0).width(pane_w).height(PV_H).child(Painting::sized(
                Size::new(pane_w, PV_H),
                PaintWith::new(move |book: &mut Sketchbook, s: Size| {
                    if alive > 0.001 && alive < 0.999 {
                        super::glow(
                            book,
                            s.width * 0.5,
                            s.height * 0.42,
                            340.0 + 260.0 * (1.0 - alive),
                            VIOLET,
                            bloom_a,
                        );
                    }
                }),
            )),
        )
        .push(
            Positioned::new().left(0.0).top(0.0).width(pane_w).height(PV_H).child(skeleton),
        )
        .push(
            Positioned::new().left(0.0).top(0.0).width(pane_w).height(PV_H).child(
                Opacity::new(alive).child(app_stack),
            ),
        )
        .into()
}

// ── The editor ──────────────────────────────────────────────────────────────

/// The editor pane: tab row, gutter, code lines, caret, optional sweep.
/// `tab` overrides the buffer tab's name.
pub fn editor(code: &Code, blur: f32, err_token: Option<(usize, usize)>, tab: Option<&str>) -> WidgetNode {
    let w = ED_X1 - ED_X0;
    let mut stack = Stack::new();

    // Tab row.
    let tab_name = tab.unwrap_or(match code {
        Code::Rust { .. } => "counter.rs",
        Code::Lines { lines, .. } => {
            // The bespoke buffers name themselves by their first `say:`-style
            // line if the scene hasn't overridden the tab.
            let _ = lines;
            "buffer.say"
        }
        _ => "counter.say",
    });
    stack = stack.push(Positioned::new().left(0.0).top(0.0).width(w).height(44.0).child(
        Painting::sized(Size::new(w, 44.0), PaintWith::new(move |book: &mut Sketchbook, s: Size| {
            book.rect(xywh(0.0, 0.0, s.width, 44.0), alpha(Color::rgb(13, 13, 17), 0.9));
            book.rect(xywh(0.0, 43.0, s.width, 1.0), alpha(Color::WHITE, 0.06));
        })),
    ));
    stack = stack
        .push(
            Positioned::new().left(14.0).top(9.0).width(240.0).height(28.0).child(
                Container::new()
                    .color(alpha(Color::rgb(26, 24, 36), 0.95))
                    .radius(8.0)
                    .border(vieww_foundation::Border::new(alpha(VIOLET_SOFT, 0.35), 1.0))
                    .child(
                        Text::new(tab_name)
                            .style(TextStyle::new(15.0).monospace().color(alpha(INK, 0.9)))
                            .align(TextAlign::Center),
                    ),
            ),
        )
        .push(
            Positioned::new().left(272.0).top(13.0).width(300.0).height(22.0).child(
                Text::new("+ say buffer").style(
                    TextStyle::new(13.5).monospace().color(alpha(FAINT, 0.7)),
                ),
            ),
        );

    // The code area.
    let (lines, typed_chars, sweep) = display_lines(code);
    let n_lines = lines.len();

    let mut code_stack = Stack::new();
    for i in 0..n_lines {
        code_stack = code_stack.push(
            Positioned::new()
                .left(8.0)
                .top(10.0 + i as f32 * CODE_LH)
                .width(50.0)
                .height(26.0)
                .child(mono((i + 1).to_string(), 15.0, alpha(FAINT, 0.5))),
        );
    }

    // The lines themselves — typed prefix in say mode, full lines otherwise.
    let mut chars_used = 0usize;
    for (li, line) in lines.iter().enumerate() {
        let mut x = 0.0f32;
        for (seg_text, seg_color) in line {
            let seg_chars = seg_text.chars().count();
            let visible_from = chars_used;
            chars_used += seg_chars;
            let typed_ok = match typed_chars {
                None => true,
                Some(t) => t >= visible_from,
            };
            if !typed_ok {
                let t = typed_chars.unwrap();
                let part = t.saturating_sub(visible_from);
                if part > 0 {
                    let prefix: String = seg_text.chars().take(part).collect();
                    code_stack = code_stack.push(
                        Positioned::new()
                            .left(CODE_X + x)
                            .top(10.0 + li as f32 * CODE_LH)
                            .width(super::mono_w(CODE_SIZE, part) + 8.0)
                            .height(28.0)
                            .child(mono(prefix, CODE_SIZE, *seg_color)),
                    );
                }
                continue;
            }
            code_stack = code_stack.push(
                Positioned::new()
                    .left(CODE_X + x)
                    .top(10.0 + li as f32 * CODE_LH)
                    .width(super::mono_w(CODE_SIZE, seg_chars) + 8.0)
                    .height(28.0)
                    .child(mono(*seg_text, CODE_SIZE, *seg_color)),
            );
            x += super::mono_w(CODE_SIZE, seg_chars);
        }
    }

    // The caret — rides the typing head while say types; blinks at the
    // old world's 24-in-60 cadence.
    let blink = match code {
        Code::Say { blink, .. } => Some(*blink),
        Code::SayExt { blink, .. } => Some(*blink),
        Code::Lines { blink, .. } => Some(*blink),
        _ => None,
    };
    if let (Some(t), Some(bl)) = (typed_chars, blink) {
        let (mut cx, mut cy) = (CODE_X, 10.0f32);
        let mut used = 0usize;
        'outer: for (li, line) in lines.iter().enumerate() {
            let mut x = 0.0;
            for (seg_text, _) in line {
                let n = seg_text.chars().count();
                if used + n > t {
                    let part = t - used;
                    cx = CODE_X + x + super::mono_w(CODE_SIZE, part);
                    cy = 10.0 + li as f32 * CODE_LH;
                    break 'outer;
                }
                used += n;
                x += super::mono_w(CODE_SIZE, n);
            }
        }
        let on = (bl * 2.6).fract() < 0.62;
        if on {
            code_stack = code_stack.push(
                Positioned::new().left(cx).top(cy + 3.0).width(2.6).height(24.0).child(
                    Container::new().color(alpha(VIOLET_SOFT, 0.9)).radius(1.3),
                ),
            );
        }
    }

    // The error token underline — a red wave under the offending word.
    if let Some((line_i, char_i)) = err_token {
        let y = 10.0 + line_i as f32 * CODE_LH + 27.0;
        let x = CODE_X + super::mono_w(CODE_SIZE, char_i);
        let wlen = super::mono_w(CODE_SIZE, 5);
        code_stack = code_stack.push(
            Positioned::new().left(x).top(y).width(wlen + 6.0).height(8.0).child(
                Painting::sized(
                    Size::new(wlen + 6.0, 8.0),
                    PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                        let mut p = vieww_foundation::Path::new();
                        p.move_to(Offset::new(0.0, 4.0));
                        let n = 6;
                        for i in 0..=n {
                            let k = i as f32 / n as f32;
                            p.line_to(Offset::new(k * wlen, if i % 2 == 0 { 1.5 } else { 5.5 }));
                        }
                        book.stroke(p, alpha(RED, 0.85), 1.6);
                    }),
                ),
            ),
        );
    }

    stack = stack.push(Positioned::new().left(0.0).top(44.0).width(w).height(940.0).child(
        Stack::new()
            .push(Positioned::fill().child(Container::new().color(alpha(Color::rgb(11, 11, 15), 0.92))))
            .push(Positioned::new().left(56.0).top(0.0).width(w - 56.0).height(940.0).child(code_stack)),
    ));

    // The sweep — a vertical scan line crossing the editor (the descent).
    if let Some(sw) = sweep {
        if sw > 0.001 && sw < 0.999 {
            let sx = sw * w;
            stack = stack.push(Positioned::new().left(0.0).top(44.0).width(w).height(940.0).child(
                Painting::sized(Size::new(w, 940.0), PaintWith::new(
                    move |book: &mut Sketchbook, s: Size| {
                        book.layer(1.0, 0.0, None, |g| {
                            g.rect(xywh(sx - 26.0, 0.0, 52.0, s.height), alpha(VIOLET, 0.10));
                        });
                        book.rrect(
                            xywh(sx - 1.2, 0.0, 2.4, s.height),
                            1.2,
                            alpha(tint(VIOLET_SOFT, 0.3), 0.85),
                        );
                    },
                )),
            ));
        }
    }

    if blur > 0.05 {
        Filtered::blur(blur).child(stack).into()
    } else {
        stack.into()
    }
}

// ── Chrome: title bar, activity bar, file tree, status bar ─────────────────

/// The viewwstudio mark — a window with a viewport and a beam of light
/// crossing it: *view* + *light*, the product in one glyph. Drawn as
/// strokes so it inherits every color the film puts it in.
pub fn draw_mark(book: &mut Sketchbook, cx: f32, cy: f32, s: f32, color: Color, a: f32) {
    let c = alpha(color, a);
    // The window.
    book.stroke_rrect(xywh(cx - s * 0.5, cy - s * 0.5, s, s), s * 0.22, c, s * 0.14);
    // The viewport — the view.
    book.stroke_rrect(
        xywh(cx - s * 0.26, cy - s * 0.26, s * 0.52, s * 0.52),
        s * 0.10,
        alpha(color, a * 0.65),
        s * 0.10,
    );
    // The beam — light through the window, corner to corner.
    let mut beam = vieww_foundation::Path::new();
    beam.move_to(Offset::new(cx + s * 0.62, cy - s * 0.62));
    beam.line_to(Offset::new(cx - s * 0.10, cy - s * 0.10));
    book.stroke_styled(
        beam,
        alpha(color, a * 0.95),
        s * 0.13,
        vieww_foundation::StrokeStyle::rounded(),
    );
    book.circle(Offset::new(cx + s * 0.62, cy - s * 0.62), s * 0.11, alpha(color, a));
}

/// The title bar — traffic dots, the mark, the app name, the platform hint.
pub fn title_bar() -> WidgetNode {
    let bar = Painting::sized(
        Size::new(1920.0, TITLE_H),
        PaintWith::new(move |book: &mut Sketchbook, s: Size| {
            book.rect(xywh(0.0, 0.0, s.width, TITLE_H), alpha(Color::rgb(15, 15, 19), 0.98));
            book.rect(xywh(0.0, TITLE_H - 1.0, s.width, 1.0), alpha(Color::WHITE, 0.05));
            let dots = [Color::rgb(255, 95, 86), Color::rgb(255, 189, 46), Color::rgb(39, 201, 63)];
            for (i, c) in dots.iter().enumerate() {
                book.circle(Offset::new(30.0 + i as f32 * 26.0, TITLE_H * 0.5), 7.0, *c);
            }
            // The mark — left of the name.
            draw_mark(book, 150.0, TITLE_H * 0.5, 26.0, VIOLET_SOFT, 0.95);
        }),
    );
    Stack::new()
        .push(Positioned::fill().child(bar))
        .push(
            Positioned::new().left(172.0).top(14.0).width(420.0).height(26.0).child(
                Text::new("viewwstudio").style(
                    TextStyle::new(16.0)
                        .monospace()
                        .letter_spacing(2.4)
                        .color(alpha(INK, 0.92)),
                ),
            ),
        )
        .push(
            Positioned::new().left(0.0).top(15.0).width(1920.0).height(24.0).child(
                Text::new("counter — a session").style(
                    TextStyle::new(14.0).monospace().letter_spacing(2.0).color(alpha(MUTED, 0.8)),
                ).align(TextAlign::Center),
            ),
        )
        .push(
            Positioned::new().left(1640.0).top(16.0).width(260.0).height(22.0).child(
                Text::new("desktop · web · phone").style(
                    TextStyle::new(12.5).monospace().color(alpha(FAINT, 0.75)),
                ),
            ),
        )
        .into()
}

/// The activity bar — the icon rail.
pub fn activity_bar(lit: usize) -> WidgetNode {
    let icons: [(Color, f32); 5] = [
        (MUTED, 44.0),
        (tint(VIOLET_SOFT, 0.2), 108.0),
        (MUTED, 172.0),
        (MUTED, 236.0),
        (MUTED, 300.0),
    ];
    let lit_f = lit as f32;
    Painting::sized(
        Size::new(ACT_W, 1080.0 - TITLE_H - STATUS_H),
        PaintWith::new(move |book: &mut Sketchbook, s: Size| {
            book.rect(xywh(0.0, 0.0, s.width, s.height), alpha(Color::rgb(13, 13, 17), 0.98));
            book.rect(xywh(s.width - 1.0, 0.0, 1.0, s.height), alpha(Color::WHITE, 0.05));
            for (idx, (c, y)) in icons.iter().enumerate() {
                let on = (idx as f32) < lit_f;
                let cc = if on { *c } else { alpha(*c, 0.45) };
                book.rect(xywh(18.0, *y, 22.0, 4.0), alpha(cc, if on { 0.9 } else { 0.8 }));
                book.rect(xywh(18.0, y + 9.0, 16.0, 4.0), alpha(cc, if on { 0.65 } else { 0.55 }));
                book.rect(xywh(18.0, y + 18.0, 19.0, 4.0), alpha(cc, if on { 0.65 } else { 0.55 }));
                if on {
                    book.rect(xywh(0.0, *y - 10.0, 3.0, 32.0), alpha(VIOLET_SOFT, 0.85));
                }
            }
        }),
    )
    .into()
}

/// The file-tree sidebar — the workspace: the counter project the session
/// edits, plus the plates the demos will drop in.
pub fn file_tree(seed: u64, t: f32, progress: f32) -> WidgetNode {
    let entries: [(&str, u8); 10] = [
        ("v counter/", 0),
        ("  Cargo.toml", 1),
        ("  counter.say", 2),
        ("  counter.rs", 3),
        ("  assets/", 1),
        ("v experiments/", 0),
        ("  swarm.say", 4),
        ("  fourier.say", 5),
        ("  plates/", 1),
        ("  receipts.txt", 3),
    ];
    let p = clamp01(progress);
    Painting::sized(
        Size::new(SIDE_W, 1080.0 - TITLE_H - STATUS_H),
        PaintWith::new(move |book: &mut Sketchbook, s: Size| {
            book.rect(xywh(0.0, 0.0, s.width, s.height), alpha(Color::rgb(12, 12, 16), 0.96));
            book.rect(xywh(s.width - 1.0, 0.0, 1.0, s.height), alpha(Color::WHITE, 0.05));
            // The workspace header.
            book.rect(xywh(0.0, 0.0, s.width, 30.0), alpha(Color::rgb(15, 15, 20), 0.9));
            book.rect(xywh(16.0, 12.0, 10.0, 10.0), alpha(VIOLET_SOFT, 0.7));
            // The entries, arriving one by one.
            let n = entries.len();
            let shown = (n as f32 * p).ceil() as usize;
            for (i, (name, kind)) in entries.iter().enumerate() {
                if i >= shown {
                    break;
                }
                let y = 52.0 + i as f32 * 30.0;
                let c = match kind {
                    0 => alpha(INK, 0.9),
                    2 | 4 | 5 => alpha(VIOLET_SOFT, 0.95),
                    3 => alpha(MUTED, 0.9),
                    _ => alpha(MUTED, 0.8),
                };
                let indent = 20.0 + if name.starts_with("  ") { 18.0 } else { 0.0 };
                // The caret / file glyph.
                if name.starts_with('v') {
                    let mut tri = vieww_foundation::Path::new();
                    tri.move_to(Offset::new(indent - 14.0, y - 4.0));
                    tri.line_to(Offset::new(indent - 14.0, y + 4.0));
                    tri.line_to(Offset::new(indent - 7.0, y));
                    tri.close();
                    book.fill(tri, alpha(MUTED, 0.8));
                } else {
                    book.rect(xywh(indent - 13.0, y - 5.0, 9.0, 11.0), alpha(FAINT, 0.55));
                }
                book.rect(xywh(indent, y - 7.0, name.trim_end_matches('/').len() as f32 * 8.4 + 8.0, 16.0), alpha(Color::TRANSPARENT, 0.0));
                let _ = c;
                // Label — drawn as mono text via thin rects is wasteful; the
                // sidebar's names ride as text nodes above this paint. Here
                // we only lay the rail's texture.
                book.rect(xywh(indent, y + 14.0, name.len().min(20) as f32 * 7.6, 1.0), alpha(Color::WHITE, 0.03));
            }
            // Breathing life — the workspace's own pulse.
            let glow_a = 0.05 + 0.03 * (t * 2.0 + seed as f32 * 0.1).sin();
            book.layer(1.0, 18.0, None, |g| {
                g.circle(
                    Offset::new(s.width * 0.5, s.height * 0.32),
                    s.width * 0.8,
                    Gradient::radial_fill().with_dither().with_stops(&[
                        (0.0, alpha(VIOLET, glow_a)),
                        (1.0, alpha(VIOLET, 0.0)),
                    ]),
                );
            });
        }),
    )
    .into()
}

/// The file-tree's name labels — text nodes over the rail's paint.
pub fn file_tree_labels(progress: f32) -> WidgetNode {
    let entries: [(&str, u8); 10] = [
        ("counter/", 0),
        ("Cargo.toml", 1),
        ("counter.say", 2),
        ("counter.rs", 3),
        ("assets/", 1),
        ("experiments/", 0),
        ("swarm.say", 4),
        ("fourier.say", 5),
        ("plates/", 1),
        ("receipts.txt", 3),
    ];
    let p = clamp01(progress);
    let n = entries.len();
    let shown = (n as f32 * p).ceil() as usize;
    let mut stack = Stack::new();
    for (i, (name, kind)) in entries.iter().enumerate() {
        if i >= shown {
            break;
        }
        let color = match kind {
            0 => alpha(INK, 0.9),
            2 | 4 | 5 => alpha(VIOLET_SOFT, 0.95),
            3 => alpha(MUTED, 0.9),
            _ => alpha(MUTED, 0.8),
        };
        let indent = 52.0 + if i == 0 || i == 5 { 18.0 } else { 36.0 };
        let y = 82.0 + i as f32 * 30.0 + TITLE_H;
        stack = stack.push(
            Positioned::new().left(indent).top(y).width(200.0).height(22.0).child(
                Text::new(*name).style(TextStyle::new(13.5).monospace().color(color)),
            ),
        );
    }
    stack.into()
}

/// The status bar — the session chip (clock + witness), the cadence, ms·px.
pub fn status_bar(abs: f32, ladder: u32, ms: Option<f32>, px: Option<u32>) -> WidgetNode {
    let pulse = 0.5 + 0.5 * (abs * 2.0).sin();
    let total_taps = super::taps().len() as u32;
    let mut stack = Stack::new().push(Positioned::fill().child(Painting::sized(
        Size::new(1920.0, STATUS_H),
        PaintWith::new(move |book: &mut Sketchbook, s: Size| {
            book.rect(xywh(0.0, 0.0, s.width, STATUS_H), alpha(Color::rgb(15, 15, 19), 0.98));
            book.rect(xywh(0.0, 0.0, s.width, 1.0), alpha(Color::WHITE, 0.05));
        }),
    )));

    stack = stack
        .push(
            Positioned::new().left(ACT_W + 10.0).top(16.0).width(14.0).height(14.0).child(
                Painting::sized(Size::new(14.0, 14.0), PaintWith::new(
                    move |book: &mut Sketchbook, _s: Size| {
                        book.circle(
                            Offset::new(7.0, 7.0),
                            4.0,
                            alpha(tint(VIOLET_SOFT, 0.2), 0.55 + 0.45 * pulse),
                        );
                        book.ring(Offset::new(7.0, 7.0), 6.5, 1.0, alpha(VIOLET_SOFT, 0.35));
                    },
                )),
            ),
        )
        .push(
            Positioned::new().left(ACT_W + 34.0).top(13.0).width(420.0).height(22.0).child(
                Text::new(format!("session {} · vieww 60 fps", super::session_clock(abs)))
                    .style(TextStyle::new(13.5).monospace().letter_spacing(1.4).color(alpha(MUTED, 0.9))),
            ),
        )
        .push(
            Positioned::new().left(520.0).top(13.0).width(220.0).height(22.0).child(
                Text::new(format!("witness {} / {}", ladder, total_taps))
                    .style(TextStyle::new(13.5).monospace().letter_spacing(1.4).color(alpha(INK, 0.75))),
            ),
        );

    if let Some(ms) = ms {
        let px_txt = match px {
            Some(p) => format!("{} px", group_commas(p as u64)),
            None => String::new(),
        };
        stack = stack.push(
            Positioned::new().left(1560.0).top(13.0).width(330.0).height(22.0).child(
                Text::new(format!("{:.1} ms · {}", ms, px_txt))
                    .style(TextStyle::new(13.5).monospace().letter_spacing(1.2).color(alpha(INK, 0.8))),
            ),
        );
    }
    stack.into()
}

// ── Assembly — the whole IDE ────────────────────────────────────────────────

/// A studio specification — what a scene wants in each pane.
pub struct Spec {
    pub code: Code,
    pub app: App,
    pub editor_blur: f32,
    pub preview_blur: f32,
    pub show_preview: bool,
    pub err_token: Option<(usize, usize)>,
    /// A custom preview sheet — the demo plates drop into the layout here.
    pub preview_custom: Option<WidgetNode>,
    /// The live build badge (frames built so far — the harness's own count).
    pub build_badge: Option<u64>,
    /// A damage rect over the preview (probe geometry), with its label.
    pub damage: Option<(Rect, String)>,
    /// The performance strip over the preview.
    pub perf_strip: bool,
    /// The session line's progress under everything.
    pub session_line: f32,
    /// Extra overlay content, drawn above the studio (scene-specific).
    pub overlay: Option<WidgetNode>,
    /// The buffer tab's name, when a scene overrides it.
    pub tab: Option<String>,
    /// ms readout for the status bar.
    pub ms: Option<f32>,
    pub px: Option<u32>,
    /// The command palette's presence (S10's flourish).
    pub palette: f32,
    /// How many activity-bar icons are lit.
    pub rail_lit: usize,
    /// The file tree's arrival progress.
    pub tree: f32,
}

impl Default for Spec {
    fn default() -> Self {
        Spec {
            code: Code::Empty,
            app: App::new(0, 0.0, 0.0),
            editor_blur: 0.0,
            preview_blur: 0.0,
            show_preview: true,
            err_token: None,
            preview_custom: None,
            build_badge: None,
            damage: None,
            perf_strip: false,
            session_line: 0.0,
            overlay: None,
            tab: None,
            ms: None,
            px: None,
            palette: 0.0,
            rail_lit: 2,
            tree: 1.0,
        }
    }
}

/// The whole studio, positioned full-bleed at master scale.
pub fn studio(abs: f32, ladder: u32, spec: Spec) -> WidgetNode {
    let Spec {
        code,
        app,
        editor_blur,
        preview_blur,
        show_preview,
        err_token,
        preview_custom,
        build_badge,
        damage,
        perf_strip: show_perf,
        session_line: line_frac,
        overlay,
        tab,
        ms,
        px,
        palette,
        rail_lit,
        tree,
    } = spec;

    let mut root = Stack::new()
        .push(Positioned::fill().child(
            Container::new().size(1920.0, 1080.0).color(alpha(Color::rgb(10, 10, 13), 1.0)),
        ))
        .push(
            Positioned::new()
                .left(0.0)
                .top(0.0)
                .width(1920.0)
                .height(TITLE_H)
                .child(title_bar()),
        )
        .push(
            Positioned::new()
                .left(0.0)
                .top(TITLE_H)
                .width(ACT_W)
                .height(1080.0 - TITLE_H - STATUS_H)
                .child(activity_bar(rail_lit)),
        )
        .push(
            Positioned::new()
                .left(ACT_W)
                .top(TITLE_H)
                .width(SIDE_W)
                .height(1080.0 - TITLE_H - STATUS_H)
                .child(file_tree(7, abs, tree)),
        )
        .push(
            Positioned::new()
                .left(ACT_W)
                .top(TITLE_H)
                .width(SIDE_W)
                .height(1080.0 - TITLE_H - STATUS_H)
                .child(file_tree_labels(tree)),
        )
        .push(
            Positioned::new()
                .left(ED_X0)
                .top(TITLE_H)
                .width(ED_X1 - ED_X0)
                .height(1080.0 - TITLE_H - STATUS_H)
                .child(editor(&code, editor_blur, err_token, tab.as_deref())),
        );

    if show_preview {
        root = root.push(
            Positioned::new()
                .left(PV_X0)
                .top(TITLE_H + 30.0)
                .width(PV_X1 - PV_X0)
                .height(PV_H + 34.0)
                .child(preview(&app, preview_blur, preview_custom)),
        );
    }

    if let Some(built) = build_badge {
        root = root.push(
            Positioned::new()
                .left(ED_X1 - 250.0)
                .top(TITLE_H + 56.0)
                .width(230.0)
                .height(36.0)
                .child(chip(format!("builds {}", group_commas(built)), 13.0, tint(VIOLET_SOFT, 0.2))),
        );
    }

    if let Some((rect, label)) = damage {
        let r = rect;
        root = root.push(Positioned::new()
            .left(PV_X0 + r.left)
            .top(TITLE_H + 64.0 + r.top)
            .width(r.width() + 4.0)
            .height(r.height() + 4.0)
            .child(Painting::sized(
                Size::new(r.width() + 4.0, r.height() + 4.0),
                PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                    book.stroke_rrect(xywh(0.0, 0.0, r.width(), r.height()), 8.0, alpha(C_DAMAGE, 0.9), 1.6);
                    book.rrect(xywh(0.0, 0.0, r.width(), r.height()), 8.0, alpha(C_DAMAGE, 0.08));
                }),
            )));
        root = root.push(
            Positioned::new()
                .left(PV_X0 + r.left)
                .top(TITLE_H + 40.0 + r.top)
                .width(420.0)
                .height(22.0)
                .child(Text::new(label).style(
                    TextStyle::new(13.0).monospace().color(alpha(tint(RED, 0.35), 0.95)),
                )),
        );
    }

    if show_perf {
        root = root.push(
            Positioned::new()
                .left(PV_X0)
                .top(TITLE_H + 46.0)
                .width(PV_X1 - PV_X0)
                .height(64.0)
                .child(perf_strip(abs)),
        );
    }

    if line_frac > 0.001 {
        let frac = line_frac;
        root = root.push(Positioned::fill().child(Painting::sized(
            Size::new(1920.0, 1080.0),
            PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                session_line(book, frac, abs);
            }),
        )));
    }

    root = root.push(
        Positioned::new()
            .left(0.0)
            .top(1080.0 - STATUS_H)
            .width(1920.0)
            .height(STATUS_H)
            .child(status_bar(abs, ladder, ms, px)),
    );

    // The command palette — S10's flourish: the studio's own spotlight.
    if palette > 0.01 {
        root = root.push(Positioned::fill().child(command_palette(palette, abs)));
    }

    if let Some(ov) = overlay {
        root = root.push(Positioned::fill().child(ov));
    }

    root.into()
}

/// The command palette — the studio's spotlight, briefly: a frosted rail
/// with the command the session is about to live.
pub fn command_palette(a: f32, abs: f32) -> WidgetNode {
    let rise = (1.0 - clamp01(a)) * 40.0;
    Opacity::new(clamp01(a)).child(
        Positioned::new()
            .left(660.0)
            .top(150.0 + rise)
            .width(600.0)
            .height(220.0)
            .child(
                Stack::new()
                    .push(Positioned::fill().child(Painting::sized(
                        Size::new(600.0, 220.0),
                        PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                            book.layer(1.0, 26.0, None, |g| {
                                g.rrect(xywh(0.0, 0.0, 600.0, 220.0), 16.0, alpha(Color::rgb(18, 17, 26), 0.88));
                            });
                            book.stroke_rrect(xywh(0.0, 0.0, 600.0, 220.0), 16.0, alpha(VIOLET_SOFT, 0.4), 1.2);
                            book.rect(xywh(28.0, 30.0, 544.0, 1.0), alpha(Color::WHITE, 0.08));
                        }),
                    )))
                    .push(Positioned::new().left(30.0).top(48.0).width(540.0).height(30.0).child(
                        Text::new("vieww: new say buffer").style(
                            TextStyle::new(21.0).monospace().color(alpha(INK, 0.95)),
                        ),
                    ))
                    .push(Positioned::new().left(30.0).top(92.0).width(540.0).height(28.0).child(
                        Text::new("vieww: build for android").style(
                            TextStyle::new(19.0).monospace().color(alpha(MUTED, 0.85)),
                        ),
                    ))
                    .push(Positioned::new().left(30.0).top(130.0).width(540.0).height(28.0).child(
                        Text::new("vieww: devtools inspector").style(
                            TextStyle::new(19.0).monospace().color(alpha(MUTED, 0.85)),
                        ),
                    ))
                    .push(Positioned::new().left(30.0).top(168.0).width(540.0).height(28.0).child(
                        Text::new(format!("session · {}", super::session_clock(abs))).style(
                            TextStyle::new(19.0).monospace().color(alpha(FAINT, 0.8)),
                        ),
                    )),
            ),
    )
    .into()
}

/// The session line — the film's spine, from the buffer to the preview and
/// onward. Nodes are touches; the stroke is the session's continuity.
pub fn session_line(book: &mut Sketchbook, frac: f32, abs: f32) {
    let y = 1006.0;
    let x0 = 214.0;
    let x1 = 1010.0;
    let pts = [
        Offset::new(x0, y),
        Offset::new(x0 + 240.0, y),
        Offset::new(x0 + 460.0, y - 44.0),
        Offset::new(x1, y - 44.0),
    ];
    let mut p = vieww_foundation::Path::new();
    p.move_to(pts[0]);
    for pt in pts.iter().skip(1) {
        p.line_to(*pt);
    }
    book.stroke(p.clone(), alpha(Color::WHITE, 0.07), 1.2);
    // The progressive stroke — one dash, phase-advanced.
    let total = 240.0 + 258.7 + 460.0;
    let draw = total * clamp01(frac);
    book.stroke_styled(
        p,
        alpha(VIOLET_SOFT, 0.9),
        2.0,
        vieww_foundation::StrokeStyle::default()
            .dash(vieww_foundation::Dash::new(vec![draw, total + 2.0])),
    );
    let nodes = [
        (x0, y, 1.0),
        (x0 + 240.0, y, 2.0),
        (x0 + 460.0, y - 44.0, 4.0),
        (x1, y - 44.0, 6.0),
    ];
    for (nx, ny, tap_n) in nodes {
        let lit = super::ladder_at(abs) >= tap_n as u32;
        book.circle(
            Offset::new(nx, ny),
            if lit { 5.0 } else { 3.0 },
            if lit { alpha(VIOLET_SOFT, 0.95) } else { alpha(MUTED, 0.3) },
        );
    }
}

/// The performance strip — FrameStats as a ribbon: frame bars + damage
/// history, all derived from the session clock.
pub fn perf_strip(abs: f32) -> WidgetNode {
    let w = PV_X1 - PV_X0;
    Painting::sized(Size::new(w, 64.0), PaintWith::new(move |book: &mut Sketchbook, s: Size| {
        book.rrect(xywh(0.0, 0.0, s.width, 64.0), 10.0, alpha(Color::rgb(14, 14, 19), 0.9));
        book.stroke_rrect(xywh(0.0, 0.0, s.width, 64.0), 10.0, alpha(Color::WHITE, 0.08), 1.0);
        let n = 60;
        let bw = (s.width - 24.0) / n as f32;
        for i in 0..n {
            let phase = abs * 6.0 - i as f32 * 0.42;
            let hgt = 8.0 + 22.0 * (0.5 + 0.5 * phase.sin());
            let x = 12.0 + i as f32 * bw;
            book.rect(
                xywh(x, 52.0 - hgt, bw * 0.66, hgt),
                if i == n - 1 { alpha(VIOLET_SOFT, 0.95) } else { alpha(VIOLET, 0.30) },
            );
        }
        let mut p = vieww_foundation::Path::new();
        for i in 0..40 {
            let k = i as f32 / 39.0;
            let x = 12.0 + k * (s.width - 24.0);
            let v = if (i as f32 * 0.7 + abs * 3.0).sin() > 0.45 { 1.0 } else { 0.12 };
            let y = 58.0 - v * 6.0;
            if i == 0 {
                p.move_to(Offset::new(x, y));
            } else {
                p.line_to(Offset::new(x, y));
            }
        }
        book.stroke(p, alpha(C_DAMAGE, 0.75), 1.4);
    }))
    .into()
}
