//! models — the film's real 3D objects, the physics it drops, and the
//! character it animates. Each one is driven by a vieww crate, not drawn
//! to look like one:
//!
//! * **The mark** is an OBJ file — written out as OBJ text at start-up
//!   and loaded back through `vieww_mesh::parse_obj`, the same loader an
//!   app would use for an asset on disk — then lit and painter-sorted
//!   triangle by triangle through [`space::View`](super::space::View).
//! * **The coins** in the opening fall through `vieww_physics::World`: a
//!   fixed-step simulation, replayed from the scene's first frame, so a
//!   frame is still a pure function of its time.
//! * **The figure** in the "what's new" scene is a `vieww_animation`
//!   skeleton: bones, a keyframed clip, world transforms composed down
//!   the chain.

use std::sync::OnceLock;

use vieww_foundation::{Color, Offset, Path, Sketchbook};

use crate::product_film as pf;
use crate::three_d::Vec3;
use super::space::View;

// ── The mark, as an OBJ ────────────────────────────────────────────────────

/// The vieww "V", as a closed polygon (x right, y up, unit half-width).
const MARK: [(f32, f32); 7] = [
    (-1.0, 1.0),
    (-0.58, 1.0),
    (0.0, -0.18),
    (0.58, 1.0),
    (1.0, 1.0),
    (0.2, -1.0),
    (-0.2, -1.0),
];

/// The cap's convex pieces, as indices into [`MARK`].
const MARK_PIECES: [&[usize]; 3] = [&[0, 1, 2, 6], &[2, 5, 6], &[2, 3, 4, 5]];

/// The mark as OBJ text: an extrusion of [`MARK`], `depth` thick, with
/// every face wound outward.
pub fn mark_obj(depth: f32) -> String {
    let n = MARK.len();
    let area: f32 = (0..n)
        .map(|i| {
            let (a, b) = (MARK[i], MARK[(i + 1) % n]);
            a.0 * b.1 - b.0 * a.1
        })
        .sum();
    let ccw = area > 0.0;
    let d = depth * 0.5;
    let mut s = String::from("# vieww mark — generated by studio_film::models\no mark\n");
    // 1..=n: front (z = +d); n+1..=2n: back (z = -d).
    for (x, y) in MARK {
        s.push_str(&format!("v {x:.4} {y:.4} {d:.4}\n"));
    }
    for (x, y) in MARK {
        s.push_str(&format!("v {x:.4} {y:.4} {:.4}\n", -d));
    }
    let face = |s: &mut String, idx: &[usize]| {
        s.push('f');
        for i in idx {
            s.push_str(&format!(" {}", i + 1));
        }
        s.push('\n');
    };
    // Caps: front faces +z, back faces -z.
    for piece in MARK_PIECES {
        let mut front: Vec<usize> = piece.to_vec();
        if !ccw {
            front.reverse();
        }
        let back: Vec<usize> = front.iter().rev().map(|i| i + n).collect();
        face(&mut s, &front);
        face(&mut s, &back);
    }
    // Sides: one quad per edge, outward.
    for i in 0..n {
        let j = (i + 1) % n;
        let q = if ccw { [i + n, j + n, j, i] } else { [j + n, i + n, i, j] };
        face(&mut s, &q);
    }
    s
}

/// The mark drawn flat: the same polygon, filled with the brand
/// gradient, `half` px from centre to its outer corners.
pub fn draw_mark_2d(book: &mut Sketchbook, c: Offset, half: f32, a: f32) {
    let a = a.clamp(0.0, 1.0);
    if a <= 0.01 {
        return;
    }
    let mut path = Path::new();
    for (i, (x, y)) in MARK.iter().enumerate() {
        let p = Offset::new(c.dx + x * half, c.dy - y * half);
        if i == 0 {
            path.move_to(p);
        } else {
            path.line_to(p);
        }
    }
    path.close();
    book.fill(
        path,
        vieww_foundation::Gradient::vertical().with_stops(&[
            (0.0, pf::alpha(super::BRAND_FAR, a)),
            (1.0, pf::alpha(super::BRAND_NEAR, a)),
        ]),
    );
}

/// The mark, loaded through the real OBJ loader once.
pub fn mark_mesh() -> &'static vieww_mesh::Mesh {
    static MESH: OnceLock<vieww_mesh::Mesh> = OnceLock::new();
    MESH.get_or_init(|| vieww_mesh::parse_obj(&mark_obj(0.42)).expect("the mark's OBJ parses"))
}

/// Where a mesh sits: scale, then pitch (about x), then yaw (about y),
/// then a move.
#[derive(Clone, Copy)]
pub struct Pose3 {
    pub scale: f32,
    pub pitch: f32,
    pub yaw: f32,
    pub at: Vec3,
}

/// How a mesh is lit.
#[derive(Clone, Copy)]
pub struct Look {
    pub near: Color,
    pub far: Color,
    pub alpha: f32,
    /// Direction *toward* the light.
    pub light: Vec3,
}

impl Look {
    pub fn brand(alpha: f32) -> Look {
        Look {
            near: super::BRAND_NEAR,
            far: super::BRAND_FAR,
            alpha,
            light: Vec3::new(-0.5, 0.7, -0.6).norm(),
        }
    }
}

/// Draw a loaded mesh: transform, cull back faces, sort far to near,
/// shade each triangle (Lambert + a Blinn glint), fill.
pub fn draw_mesh(book: &mut Sketchbook, view: &View, mesh: &vieww_mesh::Mesh, pose: Pose3, look: Look) {
    let a = look.alpha.clamp(0.0, 1.0);
    if a <= 0.01 {
        return;
    }
    let world: Vec<Vec3> = mesh
        .positions
        .iter()
        .map(|p| {
            Vec3::new(p[0], p[1], p[2])
                .scale(pose.scale)
                .rot_x(pose.pitch)
                .rot_y(pose.yaw)
                .add(pose.at)
        })
        .collect();
    let eye = view.cam.eye;
    let mut tris: Vec<(f32, [Offset; 3], Color)> = Vec::new();
    for tri in mesh.indices.chunks(3) {
        let (p0, p1, p2) = (world[tri[0] as usize], world[tri[1] as usize], world[tri[2] as usize]);
        let n = p1.sub(p0).cross(p2.sub(p0)).norm();
        let c = p0.add(p1).add(p2).scale(1.0 / 3.0);
        let to_eye = eye.sub(c).norm();
        if n.dot(to_eye) <= 0.0 {
            continue;
        }
        let (Some((s0, d0, _)), Some((s1, d1, _)), Some((s2, d2, _))) =
            (view.project(p0), view.project(p1), view.project(p2))
        else {
            continue;
        };
        let lambert = n.dot(look.light).max(0.0);
        let half = look.light.add(to_eye).norm();
        let spec = n.dot(half).max(0.0).powf(24.0) * 0.55;
        // The face's hue: the brand's two ends, picked by how it faces up.
        let hue = pf::mix(look.near, look.far, (0.5 + 0.5 * n.y).clamp(0.0, 1.0));
        let lit = (0.48 + 0.72 * lambert).min(1.25);
        let base = Color::rgba(
            (hue.r as f32 * lit).min(255.0) as u8,
            (hue.g as f32 * lit).min(255.0) as u8,
            (hue.b as f32 * lit).min(255.0) as u8,
            255,
        );
        let col = pf::mix(base, Color::WHITE, spec.min(1.0));
        tris.push(((d0 + d1 + d2) / 3.0, [s0, s1, s2], col));
    }
    tris.sort_by(|x, y| y.0.partial_cmp(&x.0).unwrap_or(std::cmp::Ordering::Equal));
    book.layer(a, 0.0, None, |b| {
        for (_, pts, col) in &tris {
            let mut path = Path::new();
            path.move_to(pts[0]).line_to(pts[1]).line_to(pts[2]);
            path.close();
            b.fill(path.clone(), *col);
            // A hairline in the face's own colour closes the seam between
            // neighbouring triangles.
            b.stroke(path, *col, 0.9);
        }
    });
}

/// Triangles and vertices of a mesh — the numbers the film may print.
pub fn mesh_counts(mesh: &vieww_mesh::Mesh) -> (usize, usize) {
    (mesh.triangles(), mesh.positions.len())
}

// ── Coins, through the physics engine ──────────────────────────────────────

/// A jar: its inner rect (left, top, right, bottom), in scene units.
#[derive(Clone, Copy)]
pub struct Jar {
    pub left: f32,
    pub top: f32,
    pub right: f32,
    pub bottom: f32,
}

/// One coin: when it drops (seconds), from where (x), and its radius.
#[derive(Clone, Copy)]
pub struct Drop {
    pub at: f32,
    pub x: f32,
    pub r: f32,
    /// Which group it belongs to (the caller's colour key).
    pub gate: usize,
}

/// Replay the jar from its first drop to `sec`, returning each dropped
/// coin's position (in drop order). Fixed 1/240 s steps; a coin enters
/// the world on the step its time comes up.
pub fn coins_at(jar: Jar, drops: &[Drop], sec: f32) -> Vec<(usize, Offset)> {
    use vieww_physics::{Body, Shape, World};
    const DT: f32 = 1.0 / 240.0;
    let mut world = World::with_gravity(Offset::new(0.0, 2400.0));
    let wall = 400.0;
    let (w, h) = (jar.right - jar.left, jar.bottom - jar.top);
    // The floor and the two walls — fixed, thick, so nothing tunnels.
    world.add_body(Body::fixed(
        Offset::new(jar.left + w * 0.5, jar.bottom + wall * 0.5),
        Shape::box_shape(w + wall * 2.0, wall),
    ));
    world.add_body(Body::fixed(
        Offset::new(jar.left - wall * 0.5, jar.top + h * 0.5 - 600.0),
        Shape::box_shape(wall, h + 1200.0),
    ));
    world.add_body(Body::fixed(
        Offset::new(jar.right + wall * 0.5, jar.top + h * 0.5 - 600.0),
        Shape::box_shape(wall, h + 1200.0),
    ));
    let fixed = world.len();
    let mut order: Vec<usize> = Vec::new();
    let mut still: Vec<f32> = Vec::new();
    let mut next = 0usize;
    let steps = (sec / DT).floor().max(0.0) as usize;
    for step in 0..=steps {
        let now = step as f32 * DT;
        while next < drops.len() && drops[next].at <= now {
            let d = drops[next];
            let body = Body::dynamic(Offset::new(d.x, jar.top - 36.0), Shape::circle(d.r), d.r * d.r * 0.01)
                .restitution(0.18);
            let mut body = body;
            body.velocity = Offset::new(0.0, 380.0);
            world.add_body(body);
            still.push(0.0);
            order.push(next);
            next += 1;
        }
        if step == steps {
            break;
        }
        world.step(DT);
        // A touch of air: coins on a pile come to rest instead of
        // sloshing forever (this solver has no friction of its own).
        for i in fixed..world.len() {
            let b = world.body_mut(i);
            if !b.is_dynamic() {
                continue;
            }
            b.velocity = Offset::new(b.velocity.dx * 0.992, b.velocity.dy * 0.998);
            // Sleep: a coin that has stayed slow for a moment is at rest,
            // and is frozen there. Without this, a pile resolved by a
            // single-pass solver with no friction keeps trembling forever.
            let speed = (b.velocity.dx * b.velocity.dx + b.velocity.dy * b.velocity.dy).sqrt();
            let k = i - fixed;
            if speed < 40.0 {
                still[k] += DT;
            } else {
                still[k] = 0.0;
            }
            if still[k] > 0.25 {
                b.mass = 0.0;
                b.velocity = Offset::new(0.0, 0.0);
            }
        }
    }
    order
        .iter()
        .enumerate()
        .map(|(k, &di)| (di, world.body(fixed + k).position))
        .collect()
}

// ── The figure, on a skeleton ──────────────────────────────────────────────

/// A small waving figure: hips → spine → head, two arms of two bones,
/// two legs. Returns the bones' world joints as (from, to) segments and
/// the head's centre, for the time `sec`.
pub fn figure_at(sec: f32, origin: Offset, scale: f32) -> (Vec<(Offset, Offset, f32)>, Offset) {
    use std::time::Duration;
    use vieww_animation::{BoneTransform as B, Keyframe, Keyframes, SkeletalClip, Skeleton};
    let t = |x: f32, y: f32| B::from_translation(Offset::new(x, y));
    let rot = |x: f32, y: f32, r: f32| B { translation: Offset::new(x, y), rotation: r, scale: (1.0, 1.0) };
    let sk = Skeleton::new()
        .bone("hips", None, t(0.0, 0.0))
        .bone("spine", Some("hips"), t(0.0, -60.0))
        .bone("neck", Some("spine"), t(0.0, -52.0))
        .bone("arm_l", Some("spine"), rot(-6.0, -48.0, 2.4))
        .bone("fore_l", Some("arm_l"), rot(46.0, 0.0, 0.3))
        .bone("hand_l", Some("fore_l"), t(42.0, 0.0))
        .bone("arm_r", Some("spine"), rot(6.0, -48.0, 0.75))
        .bone("fore_r", Some("arm_r"), rot(46.0, 0.0, -0.3))
        .bone("hand_r", Some("fore_r"), t(42.0, 0.0))
        .bone("leg_l", Some("hips"), rot(-12.0, 0.0, 1.75))
        .bone("shin_l", Some("leg_l"), rot(56.0, 0.0, -0.1))
        .bone("foot_l", Some("shin_l"), t(54.0, 0.0))
        .bone("leg_r", Some("hips"), rot(12.0, 0.0, 1.39))
        .bone("shin_r", Some("leg_r"), rot(56.0, 0.0, 0.1))
        .bone("foot_r", Some("shin_r"), t(54.0, 0.0));
    // A one-second loop: the right arm waves, the forearm answers it,
    // the body bobs and the left arm swings.
    let wave = |a: f32, b: f32| {
        Keyframes::new(rot(6.0, -48.0, a))
            .with(Keyframe::to(0.5, rot(6.0, -48.0, b)))
            .with(Keyframe::to(1.0, rot(6.0, -48.0, a)))
    };
    let clip = SkeletalClip::new()
        .bone("arm_r", wave(-0.55, -1.05))
        .bone(
            "fore_r",
            Keyframes::new(rot(46.0, 0.0, -0.9))
                .with(Keyframe::to(0.5, rot(46.0, 0.0, -0.2)))
                .with(Keyframe::to(1.0, rot(46.0, 0.0, -0.9))),
        )
        .bone(
            "hips",
            Keyframes::new(t(0.0, 0.0))
                .with(Keyframe::to(0.5, t(0.0, -6.0)))
                .with(Keyframe::to(1.0, t(0.0, 0.0))),
        )
        .bone(
            "arm_l",
            Keyframes::new(rot(-6.0, -48.0, 2.25))
                .with(Keyframe::to(0.5, rot(-6.0, -48.0, 2.55)))
                .with(Keyframe::to(1.0, rot(-6.0, -48.0, 2.25))),
        );
    let local = sec.rem_euclid(1.0);
    let pose = clip.pose(&sk, Duration::from_secs_f32(local));
    let world = sk.world(&pose);
    let joint = |name: &str| {
        let i = sk.index_of(name).expect("bone");
        let p = world[i].apply(Offset::new(0.0, 0.0));
        Offset::new(origin.dx + p.dx * scale, origin.dy + p.dy * scale)
    };
    let pairs: [(&str, &str, f32); 13] = [
        ("hips", "spine", 16.0),
        ("spine", "neck", 14.0),
        ("spine", "arm_l", 10.0),
        ("arm_l", "fore_l", 10.0),
        ("fore_l", "hand_l", 9.0),
        ("spine", "arm_r", 10.0),
        ("arm_r", "fore_r", 10.0),
        ("fore_r", "hand_r", 9.0),
        ("hips", "leg_l", 11.0),
        ("leg_l", "shin_l", 11.0),
        ("shin_l", "foot_l", 10.0),
        ("hips", "leg_r", 11.0),
        ("leg_r", "shin_r", 11.0),
    ];
    let mut segs: Vec<(Offset, Offset, f32)> =
        pairs.iter().map(|(a, b, w)| (joint(a), joint(b), w * scale)).collect();
    segs.push((joint("shin_r"), joint("foot_r"), 10.0 * scale));
    let neck = joint("neck");
    let spine = joint("spine");
    let (dx, dy) = (neck.dx - spine.dx, neck.dy - spine.dy);
    let len = (dx * dx + dy * dy).sqrt().max(1.0);
    let head = Offset::new(neck.dx + dx / len * 30.0 * scale, neck.dy + dy / len * 30.0 * scale);
    (segs, head)
}
