[package]
name = "feature-audio-reactive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
vieww-audio.workspace = true
vieww-foundation.workspace = true
feature-harness = { path = "../harness" }
vieww-widget.workspace = true

[lints]
workspace = true
