[package]
name = "three-social-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
three-app.workspace = true
three-social.workspace = true
three-runtime.workspace = true
three-core.workspace = true
vieww-integration = { path = "../vieww-integration" }
vieww.workspace = true
vieww-platform-winit.workspace = true
