//! studio — the viewwstudio kit: the IDE mock every session scene is dressed
//! in, and the counter app it edits. The grammar is inherited from the lab's
//! studio-facing plates (damage, scrub, rackfocus, morph), rebuilt at master
//! scale for the film.
//!
//! The mock is honest about what it is: a vieww widget tree standing in for
//! the product's chrome, rendered by the same rasterizer the product uses —
//! the film's own meta-claim (K5) covers it. Continuity markers per §4:
//! the buffer tab `counter`, the session chip (elapsed, emitted), the
//! witness counter, and the session line live in every studio scene.

use vieww_foundation::{
    Color, FontWeight, Gradient, Offset, Rect, Size, Sketchbook, TextAlign, TextStyle,
};
use vieww_widget::prelude::*;
use vieww_widget::{Opacity, PaintWith, Painting};

use crate::film_lib::{
    alpha, clamp01, mix, spring_out, tint, xywh, AMBER, CYAN, CYAN_SOFT, FAINT, INK, MINT, MUTED,
    RED, VIOLET, VIOLET_SOFT,
};

use super::{chip, group_commas, mono, C_DAMAGE};

// ── Geometry — the studio grid at 1920×1080 ────────────────────────────────

pub(crate) const TITLE_H: f32 = 48.0;
pub(crate) const STATUS_H: f32 = 46.0;
pub(crate) const ACT_W: f32 = 58.0;
/// Editor pane: from the activity bar to the mid gutter.
pub(crate) const ED_X0: f32 = ACT_W;
pub(crate) const ED_X1: f32 = 940.0;
/// Preview pane.
pub(crate) const PV_X0: f32 = 962.0;
pub(crate) const PV_X1: f32 = 1862.0;
/// Code origin (inside gutter).
pub(crate) const CODE_X: f32 = 124.0;
pub(crate) const CODE_SIZE: f32 = 21.0;
pub(crate) const CODE_LH: f32 = 37.0;
/// The preview pane's inner height (the glass).
pub(crate) const PV_H: f32 = 924.0;

/// The code plain-text tone — brighter than muted, dimmer than ink.
pub(crate) const CODE_PLAIN: Color = Color::rgb(196, 205, 214);

// ── The two buffers — say, and its descent ─────────────────────────────────

/// One tokenized code line: text run + color.
pub(crate) type Seg = (&'static str, Color);

/// The counter buffer in say — verbatim grammar from the studio's own
/// `06-say.md` (the film's first shown code; K0 rides on it).
pub(crate) fn say_lines() -> Vec<Vec<Seg>> {
    let kw = VIOLET_SOFT;
    let st = AMBER;
    let nu = MINT;
    let tx = CODE_PLAIN;
    let pu = MUTED;
    vec![
        vec![
            ("keep ", kw),
            ("a whole number called ", tx),
            ("count", tx),
            (" starting at ", pu),
            ("0", nu),
        ],
        vec![],
        vec![("screen ", kw), ("\"Home\"", st), (":", pu)],
        vec![
            ("    a column, spaced ", pu),
            ("16", nu),
            (", children aligned to the start:", pu),
        ],
        vec![("        a heading ", pu), ("\"Counter\"", st)],
        vec![("        a label ", pu), ("\"Tapped \\(count) times\"", st)],
        vec![
            ("        a button ", pu),
            ("\"Add one\"", st),
            (" which when tapped:", pu),
        ],
        vec![("            add ", kw), ("1", nu), (" to count", tx)],
    ]
}

/// The same buffer, descended — the generated Rust, annotated the way
/// `say-codegen` annotates (`// say: file:line`), state held across the
/// switch. The counter never resets through the morph (E-06).
pub(crate) fn rust_lines() -> Vec<Vec<Seg>> {
    let cm = FAINT;
    let at = VIOLET;
    let kw = VIOLET_SOFT;
    let ty = CYAN;
    let st = AMBER;
    let nu = MINT;
    let tx = CODE_PLAIN;
    let pu = MUTED;
    vec![
        vec![("// say: counter.say — generated by vieww-say-codegen", cm)],
        vec![("#[vieww::keep]", at)],
        vec![
            ("static ", kw),
            ("COUNT", ty),
            (": ", pu),
            ("Signal", ty),
            ("<", pu),
            ("u32", ty),
            ("> = ", pu),
            ("Signal", ty),
            ("::new(", pu),
            ("0", nu),
            (");", pu),
        ],
        vec![],
        vec![
            ("#[vieww::screen(name = ", at),
            ("\"Home\"", st),
            (")]", at),
        ],
        vec![
            ("fn ", kw),
            ("home", tx),
            ("() -> ", pu),
            ("impl Widget", ty),
            (" {", pu),
        ],
        vec![
            ("    column", ty),
            ("(", pu),
            ("16", nu),
            (").align_start().children([", pu),
        ],
        vec![
            ("        heading", ty),
            ("(", pu),
            ("\"Counter\"", st),
            ("),", pu),
        ],
        vec![
            ("        label", ty),
            ("(", pu),
            ("format!(", pu),
            ("\"Tapped {} times\"", st),
            (", ", pu),
            ("*COUNT.get())", tx),
        ],
        vec![
            ("        button", ty),
            ("(", pu),
            ("\"Add one\"", st),
            (").on_tap(||", pu),
        ],
        vec![
            ("            *COUNT.update(", tx),
            ("|c| c + ", pu),
            ("1", nu),
            ("))),", tx),
        ],
        vec![("    ])", pu)],
        vec![("}", pu)],
    ]
}

/// Which buffer the editor holds.
pub(crate) enum Code {
    /// say, typed on — `typed` in `[0, 1]` is the type-on progress,
    /// `blink` the caret's 24-in-60 blink phase.
    Say { typed: f32, blink: f32 },
    /// say, base complete, plus scene-provided extra lines (the buffer
    /// growing under live keystrokes — S06). `lines` are already sliced
    /// to whatever the scene wants visible; the caret rides their end.
    SayExt { blink: f32, lines: Vec<Vec<Seg>> },
    /// Rust, resolving under the sweep — `sweep` in `[0, 1]` is how far the
    /// scan line has crossed the editor; a line flips once it has passed.
    Rust { sweep: f32 },
    /// Nothing yet — the buffer before the first keystroke.
    Empty,
}

/// The resolved display lines for a code state, with (line-flip) progress.
fn display_lines(code: &Code) -> (Vec<Vec<Seg>>, Option<usize>, Option<f32>) {
    match code {
        Code::Say { typed, .. } => {
            let all = say_lines();
            let total: usize = all
                .iter()
                .map(|l| l.iter().map(|(s, _)| s.chars().count()).sum::<usize>())
                .sum();
            let typed_n = (total as f32 * typed.clamp(0.0, 1.0)).round() as usize;
            (all, Some(typed_n), None)
        }
        Code::SayExt { lines, .. } => {
            let mut all = say_lines();
            let extras = lines.clone();
            all.extend(extras);
            // The caret rides the end of everything typed.
            let total: usize = all
                .iter()
                .map(|l| l.iter().map(|(s, _)| s.chars().count()).sum::<usize>())
                .sum();
            (all, Some(total), None)
        }
        Code::Rust { sweep } => {
            let say = say_lines();
            let rust = rust_lines();
            let n = rust.len();
            let mut lines = Vec::with_capacity(n);
            for (i, rline) in rust.iter().enumerate() {
                let passed = *sweep >= (i + 1) as f32 / n as f32;
                if passed {
                    lines.push(rline.clone());
                } else if i < say.len() {
                    lines.push(say[i].clone());
                } else {
                    lines.push(vec![]);
                }
            }
            (lines, None, Some(*sweep))
        }
        Code::Empty => (vec![], None, None),
    }
}

// ── The counter app — the preview's content ────────────────────────────────

/// The preview's app state, all derived from the film's own clocks.
pub(crate) struct App {
    /// The witness counter — what the app shows.
    pub number: u32,
    /// Bloom on the number right after a tap (tap_pulse).
    pub flash: f32,
    /// The dial's presence, `[0, 1]` — S06 grows it.
    pub dial: f32,
    /// The spring toy's phase source (absolute film seconds — the spring
    /// never restarts, that is the whole point of S08).
    pub spring_abs: f32,
    /// The spring toy's presence.
    pub spring: f32,
    /// The error boundary's presence, `[0, 1]` — a boundary, not a crash.
    pub error: f32,
    /// The app's alive-bloom (S04's first paint).
    pub alive: f32,
    /// The column's spacing re-flow (S08's edit: 16 → 24) — the carry
    /// demonstrated as layout shift while state holds.
    pub spacing: f32,
}

impl App {
    pub(crate) fn new(number: u32, flash: f32, abs: f32) -> App {
        App {
            number,
            flash,
            dial: 0.0,
            spring_abs: abs,
            spring: 0.0,
            error: 0.0,
            alive: 1.0,
            spacing: 0.0,
        }
    }
}

/// The button's rect in preview-local coordinates — the damage probe's
/// ground truth. One place declares it; the scene and the overlay agree.
pub(crate) fn button_rect() -> Rect {
    xywh(237.0, 478.0, 246.0, 64.0)
}

/// A local circle path (the painter's own space).
fn circle_local(cx: f32, cy: f32, r: f32) -> vieww_foundation::Path {
    super::circle_path(cx, cy, r, 36)
}

/// The preview panel: frosted glass, the counter app inside.
pub(crate) fn preview(app: &App, blur: f32) -> WidgetNode {
    let alive = clamp01(app.alive);
    let number = app.number;
    let flash = app.flash;
    let dial = clamp01(app.dial);
    let spring_p = clamp01(app.spring);
    let spring_abs = app.spring_abs;
    let error = clamp01(app.error);

    // The app content — heading, label, the number, the button, the toys.
    // Softer drop than the lab plate: at master scale a 10px settle reads
    // as arrival, 26px read as a glitch (the S04 audit's note).
    let num_spring = spring_out(clamp01(flash * 3.0), 12.0, 0.58);
    let num_y = (1.0 - num_spring) * 10.0;
    let num_color = mix(INK, tint(VIOLET_SOFT, 0.3), flash.min(1.0));

    let mut app_stack = Stack::new()
        .push(
            Positioned::new()
                .left(96.0)
                .top(88.0)
                .width(600.0)
                .height(52.0)
                .child(
                    Text::new("Counter").style(
                        TextStyle::new(38.0)
                            .weight(FontWeight::Medium)
                            .letter_spacing(1.0)
                            .color(INK),
                    ),
                ),
        )
        .push(
            Positioned::new()
                .left(98.0)
                .top(148.0)
                .width(600.0)
                .height(30.0)
                .child(
                    Text::new(format!("Tapped {} times", number))
                        .style(TextStyle::new(21.0).monospace().color(MUTED)),
                ),
        )
        .push(
            Positioned::new()
                .left(0.0)
                .top(196.0 + num_y)
                .width(PV_X1 - PV_X0)
                .height(190.0)
                .child(
                    Text::new(number.to_string())
                        .style(
                            TextStyle::new(148.0)
                                .monospace()
                                .weight(FontWeight::Medium)
                                .letter_spacing(2.0)
                                .color(num_color),
                        )
                        .align(TextAlign::Center),
                ),
        );

    // The button — its rect is probe-grade (see button_rect); the column's
    // spacing re-flow (S08) shifts it down as the layout breathes.
    let press = 1.0 - 0.06 * flash;
    let spacing_shift = clamp01(app.spacing) * 26.0;
    let br = button_rect();
    app_stack = app_stack.push(
        Positioned::new()
            .left(br.left)
            .top(br.top - 40.0 + spacing_shift)
            .width(br.width())
            .height(br.height())
            .child(
                Container::new()
                    .color(alpha(VIOLET, 0.20 * press))
                    .radius(12.0)
                    .border(vieww_foundation::Border::new(alpha(VIOLET_SOFT, 0.55), 1.4))
                    .child(
                        Text::new("Add one")
                            .style(
                                TextStyle::new(23.0)
                                    .weight(FontWeight::Medium)
                                    .color(tint(VIOLET_SOFT, 0.35)),
                            )
                            .align(TextAlign::Center),
                    ),
            ),
    );

    // The dial — S06's growth. An arc gauge, count over seven.
    if dial > 0.01 {
        let cx = 700.0;
        let cy = 150.0;
        app_stack = app_stack.push(
            Positioned::new()
                .left(0.0)
                .top(0.0)
                .width(PV_X1 - PV_X0)
                .height(PV_H)
                .child(Opacity::new(dial).child(Painting::sized(
                    Size::new(PV_X1 - PV_X0, PV_H),
                    PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                        let r = 62.0;
                        book.stroke(circle_local(cx, cy, r), alpha(Color::WHITE, 0.10), 7.0);
                        let sweep = (number as f32 / 7.0).clamp(0.0, 1.0);
                        if sweep > 0.001 {
                            let mut p = vieww_foundation::Path::new();
                            p.move_to(Offset::new(cx, cy - r));
                            for i in 0..=40 {
                                let a = -std::f32::consts::FRAC_PI_2
                                    + i as f32 / 40.0 * sweep * std::f32::consts::TAU;
                                p.line_to(Offset::new(cx + a.cos() * r, cy + a.sin() * r));
                            }
                            book.stroke(p, alpha(VIOLET_SOFT, 0.85), 7.0);
                        }
                        book.circle(Offset::new(cx, cy), 4.0, tint(VIOLET_SOFT, 0.3));
                    }),
                ))),
        );
    }

    // The spring toy — a bob on a spring line, phase from the session
    // clock. It never restarts (S08's whole claim).
    if spring_p > 0.01 {
        let disp = (spring_abs * 2.4).sin() * 26.0;
        let bx = 240.0;
        let by0 = 560.0;
        app_stack = app_stack.push(
            Positioned::new()
                .left(0.0)
                .top(0.0)
                .width(PV_X1 - PV_X0)
                .height(PV_H)
                .child(Opacity::new(spring_p).child(Painting::sized(
                    Size::new(PV_X1 - PV_X0, PV_H),
                    PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                        let by = by0 + disp;
                        let mut p = vieww_foundation::Path::new();
                        p.move_to(Offset::new(bx, by0 - 64.0));
                        for i in 0..12 {
                            let k = (i + 1) as f32 / 12.0;
                            let y = by0 - 64.0 + k * (64.0 + (by - by0));
                            let wob = if i % 2 == 0 { 12.0 } else { -12.0 };
                            p.line_to(Offset::new(bx + wob, y));
                        }
                        p.line_to(Offset::new(bx, by));
                        book.stroke(p, alpha(MUTED, 0.55), 1.6);
                        book.circle(Offset::new(bx, by + 8.0), 11.0, tint(VIOLET_SOFT, 0.4));
                        book.stroke(
                            circle_local(bx, by + 8.0, 11.0),
                            alpha(Color::WHITE, 0.25),
                            1.0,
                        );
                        book.rect(
                            xywh(bx - 22.0, by0 - 70.0, 44.0, 5.0),
                            alpha(Color::WHITE, 0.18),
                        );
                    }),
                ))),
        );
    }

    // The error boundary — a boundary, not a crash (E-07). The preview holds
    // its last good frame beneath the card: nothing is lost, nothing breaks.
    if error > 0.01 {
        let e = error;
        app_stack = app_stack.push(
            Positioned::new()
                .left(96.0)
                .top(96.0)
                .width(660.0)
                .height(420.0)
                .child(Opacity::new(e).child(Painting::sized(
                    Size::new(660.0, 420.0),
                    PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                        book.rrect(
                            xywh(0.0, 0.0, 660.0, 420.0),
                            16.0,
                            alpha(Color::rgb(40, 16, 20), 0.94),
                        );
                        book.stroke_rrect(
                            xywh(0.0, 0.0, 660.0, 420.0),
                            16.0,
                            alpha(RED, 0.45),
                            1.4,
                        );
                        book.rect(xywh(0.0, 0.0, 660.0, 4.0), alpha(RED, 0.8 * e));
                    }),
                ))),
        );
        app_stack = app_stack
            .push(
                Positioned::new().left(136.0).top(150.0).width(560.0).height(40.0).child(
                    Text::new("boundary").style(
                        TextStyle::new(30.0)
                            .monospace()
                            .letter_spacing(3.0)
                            .color(tint(RED, 0.25)),
                    ),
                ),
            )
            .push(
                Positioned::new().left(136.0).top(206.0).width(540.0).height(90.0).child(
                    Text::new(
                        "expected a value after \u{201c}showing\u{d}\nthe preview holds your last good frame",
                    )
                    .style(TextStyle::new(19.0).monospace().color(alpha(INK, 0.8))),
                ),
            );
    }

    // The alive bloom — first paint glows, then settles.
    let bloom_a = 0.34 * (1.0 - alive).max(0.0) + if alive >= 0.999 { 0.0 } else { 0.05 };
    // The dormant skeleton — before the first paint, the pane is not a
    // black void but a dim wireframe of what it is waiting to become
    // (the S04 audit's note: an empty right half reads as absence, not
    // anticipation).
    let skeleton = Painting::sized(
        Size::new(PV_X1 - PV_X0, PV_H),
        PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
            let a = 0.16 * (1.0 - alive);
            if a <= 0.005 {
                return;
            }
            book.rrect(xywh(96.0, 96.0, 240.0, 34.0), 6.0, alpha(Color::WHITE, a));
            book.rrect(
                xywh(98.0, 152.0, 300.0, 18.0),
                5.0,
                alpha(Color::WHITE, a * 0.7),
            );
            book.rrect(
                xywh(360.0, 210.0, 180.0, 120.0),
                10.0,
                alpha(Color::WHITE, a),
            );
            let br = button_rect();
            book.rrect(
                xywh(br.left, br.top - 40.0, br.width(), br.height()),
                12.0,
                alpha(VIOLET, a * 0.8),
            );
            // A held spinner — the preview's waiting state.
            book.stroke_styled(
                super::circle_path(br.left + br.width() + 70.0, br.top - 8.0, 14.0, 36),
                alpha(MUTED, a * 2.4),
                2.2,
                vieww_foundation::StrokeStyle::rounded()
                    .dash(vieww_foundation::Dash::even(6.0).offset(alive * 40.0)),
            );
        }),
    );
    let content = Stack::new()
        .push(
            Positioned::new()
                .left(0.0)
                .top(0.0)
                .width(PV_X1 - PV_X0)
                .height(PV_H)
                .child(Painting::sized(
                    Size::new(PV_X1 - PV_X0, PV_H),
                    PaintWith::new(move |book: &mut Sketchbook, s: Size| {
                        if alive > 0.001 && alive < 0.999 {
                            super::glow(
                                book,
                                s.width * 0.5,
                                s.height * 0.42,
                                340.0 + 260.0 * (1.0 - alive),
                                VIOLET,
                                bloom_a,
                            );
                        }
                    }),
                )),
        )
        .push(
            Positioned::new()
                .left(0.0)
                .top(0.0)
                .width(PV_X1 - PV_X0)
                .height(PV_H)
                .child(skeleton),
        )
        .push(
            Positioned::new()
                .left(0.0)
                .top(0.0)
                .width(PV_X1 - PV_X0)
                .height(PV_H)
                .child(Opacity::new(alive).child(app_stack)),
        );

    // The glass body — frosted, tinted, bordered (light's card grammar).
    let glass = Container::new()
        .size(PV_X1 - PV_X0, PV_H)
        .radius(18.0)
        .gradient(Gradient::vertical().with_dither().with_stops(&[
            (0.0, alpha(mix(Color::WHITE, VIOLET_SOFT, 0.22), 0.055)),
            (0.55, alpha(Color::WHITE, 0.028)),
            (1.0, alpha(mix(Color::WHITE, CYAN_SOFT, 0.28), 0.045)),
        ]))
        .border(vieww_foundation::Border::new(
            alpha(Color::WHITE, 0.14),
            1.0,
        ));

    let header = Positioned::new()
        .left(4.0)
        .top(8.0)
        .width(600.0)
        .height(26.0)
        .child(
            Text::new("preview · Home").style(
                TextStyle::new(15.0)
                    .monospace()
                    .letter_spacing(2.0)
                    .color(alpha(MUTED, 0.85)),
            ),
        );

    let pane = Stack::new()
        .push(
            Positioned::new()
                .left(0.0)
                .top(34.0)
                .width(PV_X1 - PV_X0)
                .height(PV_H)
                .child(glass),
        )
        .push(
            Positioned::new()
                .left(0.0)
                .top(34.0)
                .width(PV_X1 - PV_X0)
                .height(PV_H)
                .child(content),
        )
        .push(header);

    if blur > 0.05 {
        Filtered::blur(blur).child(pane).into()
    } else {
        pane.into()
    }
}

// ── The editor ──────────────────────────────────────────────────────────────

/// The editor pane: tab row, gutter, code lines, caret, optional sweep.
/// `tab` overrides the buffer tab's name (S16's `endcard` buffer).
pub(crate) fn editor(
    code: &Code,
    blur: f32,
    err_token: Option<(usize, usize)>,
    tab: Option<&str>,
) -> WidgetNode {
    let w = ED_X1 - ED_X0;
    let mut stack = Stack::new();

    // Tab row.
    let tab_name = tab.unwrap_or(match code {
        Code::Rust { .. } => "counter.rs",
        _ => "counter.say",
    });
    stack = stack.push(
        Positioned::new()
            .left(0.0)
            .top(0.0)
            .width(w)
            .height(44.0)
            .child(Painting::sized(
                Size::new(w, 44.0),
                PaintWith::new(move |book: &mut Sketchbook, s: Size| {
                    book.rect(
                        xywh(0.0, 0.0, s.width, 44.0),
                        alpha(Color::rgb(13, 13, 17), 0.9),
                    );
                    book.rect(xywh(0.0, 43.0, s.width, 1.0), alpha(Color::WHITE, 0.06));
                }),
            )),
    );
    stack = stack
        .push(
            Positioned::new()
                .left(14.0)
                .top(9.0)
                .width(240.0)
                .height(28.0)
                .child(
                    Container::new()
                        .color(alpha(Color::rgb(26, 24, 36), 0.95))
                        .radius(8.0)
                        .border(vieww_foundation::Border::new(alpha(VIOLET_SOFT, 0.35), 1.0))
                        .child(
                            Text::new(tab_name)
                                .style(TextStyle::new(15.0).monospace().color(alpha(INK, 0.9)))
                                .align(TextAlign::Center),
                        ),
                ),
        )
        .push(
            Positioned::new()
                .left(272.0)
                .top(13.0)
                .width(300.0)
                .height(22.0)
                .child(
                    Text::new("+ say buffer")
                        .style(TextStyle::new(13.5).monospace().color(alpha(FAINT, 0.7))),
                ),
        );

    // The code area.
    let (lines, typed_chars, sweep) = display_lines(code);
    let n_lines = lines.len();

    let mut code_stack = Stack::new();
    for i in 0..n_lines {
        code_stack = code_stack.push(
            Positioned::new()
                .left(8.0)
                .top(10.0 + i as f32 * CODE_LH)
                .width(50.0)
                .height(26.0)
                .child(mono((i + 1).to_string(), 15.0, alpha(FAINT, 0.5))),
        );
    }

    // The lines themselves — typed prefix in say mode, full lines otherwise.
    let mut chars_used = 0usize;
    for (li, line) in lines.iter().enumerate() {
        let mut x = 0.0f32;
        for (seg_text, seg_color) in line {
            let seg_chars = seg_text.chars().count();
            let visible_from = chars_used;
            chars_used += seg_chars;
            let typed_ok = match typed_chars {
                None => true,
                Some(t) => t >= visible_from,
            };
            if !typed_ok {
                let t = typed_chars.unwrap();
                let part = t.saturating_sub(visible_from);
                if part > 0 {
                    let prefix: String = seg_text.chars().take(part).collect();
                    code_stack = code_stack.push(
                        Positioned::new()
                            .left(CODE_X + x)
                            .top(10.0 + li as f32 * CODE_LH)
                            .width(super::mono_w(CODE_SIZE, part) + 8.0)
                            .height(28.0)
                            .child(mono(prefix, CODE_SIZE, *seg_color)),
                    );
                }
                continue;
            }
            code_stack = code_stack.push(
                Positioned::new()
                    .left(CODE_X + x)
                    .top(10.0 + li as f32 * CODE_LH)
                    .width(super::mono_w(CODE_SIZE, seg_chars) + 8.0)
                    .height(28.0)
                    .child(mono(*seg_text, CODE_SIZE, *seg_color)),
            );
            x += super::mono_w(CODE_SIZE, seg_chars);
        }
    }

    // The caret — rides the typing head while say types; blinks at the
    // wait's own 24-in-60 cadence.
    let blink = match code {
        Code::Say { blink, .. } => Some(*blink),
        Code::SayExt { blink, .. } => Some(*blink),
        _ => None,
    };
    if let (Some(t), Some(bl)) = (typed_chars, blink) {
        let (mut cx, mut cy) = (CODE_X, 10.0f32);
        let mut used = 0usize;
        'outer: for (li, line) in lines.iter().enumerate() {
            let mut x = 0.0f32;
            for (seg_text, _) in line {
                let n = seg_text.chars().count();
                if used + n > t {
                    let part = t - used;
                    cx = CODE_X + x + super::mono_w(CODE_SIZE, part);
                    cy = 10.0 + li as f32 * CODE_LH;
                    break 'outer;
                }
                used += n;
                x += super::mono_w(CODE_SIZE, n);
            }
        }
        let on = (bl * 2.6).fract() < 0.62;
        if on {
            code_stack = code_stack.push(
                Positioned::new()
                    .left(cx)
                    .top(cy + 3.0)
                    .width(2.6)
                    .height(24.0)
                    .child(Container::new().color(alpha(VIOLET_SOFT, 0.9)).radius(1.3)),
            );
        }
    }

    // The error token underline — a red wave under the offending word.
    if let Some((line_i, char_i)) = err_token {
        let y = 10.0 + line_i as f32 * CODE_LH + 27.0;
        let x = CODE_X + super::mono_w(CODE_SIZE, char_i);
        let wlen = super::mono_w(CODE_SIZE, 5);
        code_stack = code_stack.push(
            Positioned::new()
                .left(x)
                .top(y)
                .width(wlen + 6.0)
                .height(8.0)
                .child(Painting::sized(
                    Size::new(wlen + 6.0, 8.0),
                    PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                        let mut p = vieww_foundation::Path::new();
                        p.move_to(Offset::new(0.0, 4.0));
                        let n = 6;
                        for i in 0..=n {
                            let k = i as f32 / n as f32;
                            p.line_to(Offset::new(k * wlen, if i % 2 == 0 { 1.5 } else { 5.5 }));
                        }
                        book.stroke(p, alpha(RED, 0.85), 1.6);
                    }),
                )),
        );
    }

    stack = stack.push(
        Positioned::new()
            .left(0.0)
            .top(44.0)
            .width(w)
            .height(940.0)
            .child(
                Stack::new()
                    .push(
                        Positioned::fill()
                            .child(Container::new().color(alpha(Color::rgb(11, 11, 15), 0.92))),
                    )
                    .push(
                        Positioned::new()
                            .left(56.0)
                            .top(0.0)
                            .width(w - 56.0)
                            .height(940.0)
                            .child(code_stack),
                    ),
            ),
    );

    // The sweep — a vertical scan line crossing the editor (E-06).
    if let Some(sw) = sweep {
        if sw > 0.001 && sw < 0.999 {
            let sx = sw * w;
            stack = stack.push(
                Positioned::new()
                    .left(0.0)
                    .top(44.0)
                    .width(w)
                    .height(940.0)
                    .child(Painting::sized(
                        Size::new(w, 940.0),
                        PaintWith::new(move |book: &mut Sketchbook, s: Size| {
                            book.layer(1.0, 0.0, None, |g| {
                                g.rect(xywh(sx - 26.0, 0.0, 52.0, s.height), alpha(VIOLET, 0.10));
                            });
                            book.rrect(
                                xywh(sx - 1.2, 0.0, 2.4, s.height),
                                1.2,
                                alpha(tint(VIOLET_SOFT, 0.3), 0.85),
                            );
                        }),
                    )),
            );
        }
    }

    if blur > 0.05 {
        Filtered::blur(blur).child(stack).into()
    } else {
        stack.into()
    }
}

// ── Chrome: title bar, activity bar, status bar ────────────────────────────

/// The title bar — traffic dots, the app name, the platform hint.
pub(crate) fn title_bar() -> WidgetNode {
    let bar = Painting::sized(
        Size::new(1920.0, TITLE_H),
        PaintWith::new(move |book: &mut Sketchbook, s: Size| {
            book.rect(
                xywh(0.0, 0.0, s.width, TITLE_H),
                alpha(Color::rgb(15, 15, 19), 0.98),
            );
            book.rect(
                xywh(0.0, TITLE_H - 1.0, s.width, 1.0),
                alpha(Color::WHITE, 0.05),
            );
            let dots = [
                Color::rgb(255, 95, 86),
                Color::rgb(255, 189, 46),
                Color::rgb(39, 201, 63),
            ];
            for (i, c) in dots.iter().enumerate() {
                book.circle(Offset::new(30.0 + i as f32 * 26.0, TITLE_H * 0.5), 7.0, *c);
            }
        }),
    );
    Stack::new()
        .push(Positioned::fill().child(bar))
        .push(
            Positioned::new()
                .left(0.0)
                .top(13.0)
                .width(1920.0)
                .height(26.0)
                .child(
                    Text::new("viewwstudio — counter")
                        .style(
                            TextStyle::new(15.0)
                                .monospace()
                                .letter_spacing(2.0)
                                .color(alpha(MUTED, 0.9)),
                        )
                        .align(TextAlign::Center),
                ),
        )
        .push(
            Positioned::new()
                .left(1680.0)
                .top(14.0)
                .width(220.0)
                .height(22.0)
                .child(
                    Text::new("desktop · web · phone")
                        .style(TextStyle::new(12.5).monospace().color(alpha(FAINT, 0.75))),
                ),
        )
        .into()
}

/// The activity bar — the icon rail.
pub(crate) fn activity_bar() -> WidgetNode {
    Painting::sized(
        Size::new(ACT_W, 1080.0 - TITLE_H - STATUS_H),
        PaintWith::new(move |book: &mut Sketchbook, s: Size| {
            book.rect(
                xywh(0.0, 0.0, s.width, s.height),
                alpha(Color::rgb(13, 13, 17), 0.98),
            );
            book.rect(
                xywh(s.width - 1.0, 0.0, 1.0, s.height),
                alpha(Color::WHITE, 0.05),
            );
            let icons: [(Color, f32); 5] = [
                (MUTED, 44.0),
                (tint(VIOLET_SOFT, 0.2), 108.0),
                (MUTED, 172.0),
                (MUTED, 236.0),
                (MUTED, 300.0),
            ];
            for (c, y) in icons {
                book.rect(xywh(18.0, y, 22.0, 4.0), alpha(c, 0.8));
                book.rect(xywh(18.0, y + 9.0, 16.0, 4.0), alpha(c, 0.55));
                book.rect(xywh(18.0, y + 18.0, 19.0, 4.0), alpha(c, 0.55));
            }
        }),
    )
    .into()
}

/// The status bar — the session chip (clock + witness), the cadence, ms·px.
pub(crate) fn status_bar(abs: f32, ladder: u32, ms: Option<f32>, px: Option<u32>) -> WidgetNode {
    let pulse = 0.5 + 0.5 * (abs * 2.0).sin();
    let mut stack = Stack::new().push(Positioned::fill().child(Painting::sized(
        Size::new(1920.0, STATUS_H),
        PaintWith::new(move |book: &mut Sketchbook, s: Size| {
            book.rect(
                xywh(0.0, 0.0, s.width, STATUS_H),
                alpha(Color::rgb(15, 15, 19), 0.98),
            );
            book.rect(xywh(0.0, 0.0, s.width, 1.0), alpha(Color::WHITE, 0.05));
        }),
    )));

    stack = stack
        .push(
            Positioned::new()
                .left(ACT_W + 10.0)
                .top(16.0)
                .width(14.0)
                .height(14.0)
                .child(Painting::sized(
                    Size::new(14.0, 14.0),
                    PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                        book.circle(
                            Offset::new(7.0, 7.0),
                            4.0,
                            alpha(tint(VIOLET_SOFT, 0.2), 0.55 + 0.45 * pulse),
                        );
                        book.ring(Offset::new(7.0, 7.0), 6.5, 1.0, alpha(VIOLET_SOFT, 0.35));
                    }),
                )),
        )
        .push(
            Positioned::new()
                .left(ACT_W + 34.0)
                .top(13.0)
                .width(420.0)
                .height(22.0)
                .child(
                    Text::new(format!(
                        "session {} · vieww 60 fps",
                        super::session_clock(abs)
                    ))
                    .style(
                        TextStyle::new(13.5)
                            .monospace()
                            .letter_spacing(1.4)
                            .color(alpha(MUTED, 0.9)),
                    ),
                ),
        )
        .push(
            Positioned::new()
                .left(520.0)
                .top(13.0)
                .width(220.0)
                .height(22.0)
                .child(
                    Text::new(format!("witness {} / 7", ladder)).style(
                        TextStyle::new(13.5)
                            .monospace()
                            .letter_spacing(1.4)
                            .color(alpha(INK, 0.75)),
                    ),
                ),
        );

    if let Some(ms) = ms {
        let px_txt = match px {
            Some(p) => format!("{} px", group_commas(p as u64)),
            None => String::new(),
        };
        stack = stack.push(
            Positioned::new()
                .left(1560.0)
                .top(13.0)
                .width(330.0)
                .height(22.0)
                .child(
                    Text::new(format!("{:.1} ms · {}", ms, px_txt)).style(
                        TextStyle::new(13.5)
                            .monospace()
                            .letter_spacing(1.2)
                            .color(alpha(INK, 0.8)),
                    ),
                ),
        );
    }
    stack.into()
}

// ── Assembly — the whole IDE ────────────────────────────────────────────────

/// A studio specification — what a scene wants in each pane.
pub(crate) struct Spec {
    pub code: Code,
    pub app: App,
    pub editor_blur: f32,
    pub preview_blur: f32,
    pub show_preview: bool,
    pub err_token: Option<(usize, usize)>,
    /// The live build badge (frames built so far — the harness's own count).
    pub build_badge: Option<u64>,
    /// A damage rect over the preview (probe geometry), with its label.
    pub damage: Option<(Rect, String)>,
    /// The performance strip over the preview.
    pub perf_strip: bool,
    /// The session line's progress under everything (E-17).
    pub session_line: f32,
    /// Extra overlay content, drawn above the studio (scene-specific).
    pub overlay: Option<WidgetNode>,
    /// The buffer tab's name, when a scene overrides it.
    pub tab: Option<String>,
    /// ms readout for the status bar.
    pub ms: Option<f32>,
    pub px: Option<u32>,
}

impl Default for Spec {
    fn default() -> Self {
        Spec {
            code: Code::Empty,
            app: App::new(0, 0.0, 0.0),
            editor_blur: 0.0,
            preview_blur: 0.0,
            show_preview: true,
            err_token: None,
            build_badge: None,
            damage: None,
            perf_strip: false,
            session_line: 0.0,
            overlay: None,
            tab: None,
            ms: None,
            px: None,
        }
    }
}

/// The whole studio, positioned full-bleed at master scale.
pub(crate) fn studio(abs: f32, ladder: u32, spec: Spec) -> WidgetNode {
    let Spec {
        code,
        app,
        editor_blur,
        preview_blur,
        show_preview,
        err_token,
        build_badge,
        damage,
        perf_strip: show_perf,
        session_line: line_frac,
        overlay,
        tab,
        ms,
        px,
    } = spec;

    let mut root = Stack::new()
        .push(
            Positioned::fill().child(
                Container::new()
                    .size(1920.0, 1080.0)
                    .color(alpha(Color::rgb(10, 10, 13), 1.0)),
            ),
        )
        .push(
            Positioned::new()
                .left(0.0)
                .top(0.0)
                .width(1920.0)
                .height(TITLE_H)
                .child(title_bar()),
        )
        .push(
            Positioned::new()
                .left(0.0)
                .top(TITLE_H)
                .width(ACT_W)
                .height(1080.0 - TITLE_H - STATUS_H)
                .child(activity_bar()),
        )
        .push(
            Positioned::new()
                .left(ED_X0)
                .top(TITLE_H)
                .width(ED_X1 - ED_X0)
                .height(1080.0 - TITLE_H - STATUS_H)
                .child(editor(&code, editor_blur, err_token, tab.as_deref())),
        );

    if show_preview {
        root = root.push(
            Positioned::new()
                .left(PV_X0)
                .top(TITLE_H + 30.0)
                .width(PV_X1 - PV_X0)
                .height(PV_H + 34.0)
                .child(preview(&app, preview_blur)),
        );
    }

    if let Some(built) = build_badge {
        root = root.push(
            Positioned::new()
                .left(ED_X1 - 250.0)
                .top(TITLE_H + 56.0)
                .width(230.0)
                .height(36.0)
                .child(chip(
                    format!("builds {}", group_commas(built)),
                    13.0,
                    tint(VIOLET_SOFT, 0.2),
                )),
        );
    }

    if let Some((rect, label)) = damage {
        let r = rect;
        root = root.push(
            Positioned::new()
                .left(PV_X0 + r.left)
                .top(TITLE_H + 64.0 + r.top)
                .width(r.width() + 4.0)
                .height(r.height() + 4.0)
                .child(Painting::sized(
                    Size::new(r.width() + 4.0, r.height() + 4.0),
                    PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                        book.stroke_rrect(
                            xywh(0.0, 0.0, r.width(), r.height()),
                            8.0,
                            alpha(C_DAMAGE, 0.9),
                            1.6,
                        );
                        book.rrect(
                            xywh(0.0, 0.0, r.width(), r.height()),
                            8.0,
                            alpha(C_DAMAGE, 0.08),
                        );
                    }),
                )),
        );
        root = root.push(
            Positioned::new()
                .left(PV_X0 + r.left)
                .top(TITLE_H + 40.0 + r.top)
                .width(420.0)
                .height(22.0)
                .child(
                    Text::new(label).style(
                        TextStyle::new(13.0)
                            .monospace()
                            .color(alpha(tint(RED, 0.35), 0.95)),
                    ),
                ),
        );
    }

    if show_perf {
        root = root.push(
            Positioned::new()
                .left(PV_X0)
                .top(TITLE_H + 46.0)
                .width(PV_X1 - PV_X0)
                .height(64.0)
                .child(perf_strip(abs)),
        );
    }

    if line_frac > 0.001 {
        let frac = line_frac;
        root = root.push(Positioned::fill().child(Painting::sized(
            Size::new(1920.0, 1080.0),
            PaintWith::new(move |book: &mut Sketchbook, _s: Size| {
                session_line(book, frac, abs);
            }),
        )));
    }

    root = root.push(
        Positioned::new()
            .left(0.0)
            .top(1080.0 - STATUS_H)
            .width(1920.0)
            .height(STATUS_H)
            .child(status_bar(abs, ladder, ms, px)),
    );

    if let Some(ov) = overlay {
        root = root.push(Positioned::fill().child(ov));
    }

    root.into()
}

/// The session line — the film's spine, from the buffer to the preview and
/// onward. Nodes are touches; the stroke is the session's continuity.
pub(crate) fn session_line(book: &mut Sketchbook, frac: f32, abs: f32) {
    let y = 1006.0;
    let x0 = 214.0;
    let x1 = 1010.0;
    let pts = [
        Offset::new(x0, y),
        Offset::new(x0 + 240.0, y),
        Offset::new(x0 + 460.0, y - 44.0),
        Offset::new(x1, y - 44.0),
    ];
    let mut p = vieww_foundation::Path::new();
    p.move_to(pts[0]);
    for pt in pts.iter().skip(1) {
        p.line_to(*pt);
    }
    book.stroke(p.clone(), alpha(Color::WHITE, 0.07), 1.2);
    // The progressive stroke — one dash, phase-advanced (E-17).
    let total = 240.0 + 258.7 + 460.0;
    let draw = total * clamp01(frac);
    book.stroke_styled(
        p,
        alpha(VIOLET_SOFT, 0.9),
        2.0,
        vieww_foundation::StrokeStyle::default()
            .dash(vieww_foundation::Dash::new(vec![draw, total + 2.0])),
    );
    let nodes = [
        (x0, y, 1.0),
        (x0 + 240.0, y, 2.0),
        (x0 + 460.0, y - 44.0, 4.0),
        (x1, y - 44.0, 6.0),
    ];
    for (nx, ny, tap_n) in nodes {
        let lit = super::ladder_at(abs) >= tap_n as u32;
        book.circle(
            Offset::new(nx, ny),
            if lit { 5.0 } else { 3.0 },
            if lit {
                alpha(VIOLET_SOFT, 0.95)
            } else {
                alpha(MUTED, 0.3)
            },
        );
    }
}

/// The performance strip — FrameStats as a ribbon: frame bars + damage
/// history, all derived from the session clock.
pub(crate) fn perf_strip(abs: f32) -> WidgetNode {
    let w = PV_X1 - PV_X0;
    Painting::sized(
        Size::new(w, 64.0),
        PaintWith::new(move |book: &mut Sketchbook, s: Size| {
            book.rrect(
                xywh(0.0, 0.0, s.width, 64.0),
                10.0,
                alpha(Color::rgb(14, 14, 19), 0.9),
            );
            book.stroke_rrect(
                xywh(0.0, 0.0, s.width, 64.0),
                10.0,
                alpha(Color::WHITE, 0.08),
                1.0,
            );
            let n = 60;
            let bw = (s.width - 24.0) / n as f32;
            for i in 0..n {
                let phase = abs * 6.0 - i as f32 * 0.42;
                let hgt = 8.0 + 22.0 * (0.5 + 0.5 * phase.sin());
                let x = 12.0 + i as f32 * bw;
                book.rect(
                    xywh(x, 52.0 - hgt, bw * 0.66, hgt),
                    if i == n - 1 {
                        alpha(VIOLET_SOFT, 0.95)
                    } else {
                        alpha(VIOLET, 0.30)
                    },
                );
            }
            let mut p = vieww_foundation::Path::new();
            for i in 0..40 {
                let k = i as f32 / 39.0;
                let x = 12.0 + k * (s.width - 24.0);
                let v = if (i as f32 * 0.7 + abs * 3.0).sin() > 0.45 {
                    1.0
                } else {
                    0.12
                };
                let y = 58.0 - v * 6.0;
                if i == 0 {
                    p.move_to(Offset::new(x, y));
                } else {
                    p.line_to(Offset::new(x, y));
                }
            }
            book.stroke(p, alpha(C_DAMAGE, 0.75), 1.4);
        }),
    )
    .into()
}
